/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UsersRouteImport } from './routes/users'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as MyPageRouteImport } from './routes/my-page'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as SplatRouteImport } from './routes/$'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UsersIndexRouteImport } from './routes/users/index'
import { Route as SettingsIndexRouteImport } from './routes/settings/index'
import { Route as UsersIdRouteImport } from './routes/users/$id'
import { Route as SettingsSecurityRouteImport } from './routes/settings/security'
import { Route as SettingsProfileRouteImport } from './routes/settings/profile'
import { Route as SettingsNotificationsRouteImport } from './routes/settings/notifications'
import { Route as SettingsLanguageRouteImport } from './routes/settings/language'
import { Route as SettingsCompanyAddressesRouteImport } from './routes/settings/company-addresses'
import { Route as SettingsAppearanceRouteImport } from './routes/settings/appearance'
import { Route as SettingsAccountRouteImport } from './routes/settings/account'
import { Route as SalesTestsRouteImport } from './routes/sales/tests'
import { Route as SalesCustomersRouteImport } from './routes/sales/customers'
import { Route as InventoryItemsRouteImport } from './routes/inventory/items'
import { Route as authLoginRouteImport } from './routes/(auth)/login'
import { Route as authChangePasswordRouteImport } from './routes/(auth)/change-password'
import { Route as SettingsInventoryIndexRouteImport } from './routes/settings/inventory/index'
import { Route as SalesTestsIndexRouteImport } from './routes/sales/tests/index'
import { Route as SalesCustomersIndexRouteImport } from './routes/sales/customers/index'
import { Route as InventoryItemsIndexRouteImport } from './routes/inventory/items/index'
import { Route as SettingsSalesTestTreesRouteImport } from './routes/settings/sales/test-trees'
import { Route as SettingsSalesTestBasicsRouteImport } from './routes/settings/sales/test-basics'
import { Route as SettingsSalesCustomerTypesRouteImport } from './routes/settings/sales/customer-types'
import { Route as SettingsSalesCustomerGroupsRouteImport } from './routes/settings/sales/customer-groups'
import { Route as SettingsInventoryWarehousesRouteImport } from './routes/settings/inventory/warehouses'
import { Route as SettingsInventoryUnitsRouteImport } from './routes/settings/inventory/units'
import { Route as SettingsInventoryLotsRouteImport } from './routes/settings/inventory/lots'
import { Route as SalesTestsIdRouteImport } from './routes/sales/tests/$id'
import { Route as SalesCustomersIdRouteImport } from './routes/sales/customers/$id'
import { Route as InventoryItemsIdRouteImport } from './routes/inventory/items/$id'

const UsersRoute = UsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const MyPageRoute = MyPageRouteImport.update({
  id: '/my-page',
  path: '/my-page',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersIndexRoute = UsersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => UsersRoute,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersIdRoute = UsersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => UsersRoute,
} as any)
const SettingsSecurityRoute = SettingsSecurityRouteImport.update({
  id: '/settings/security',
  path: '/settings/security',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsProfileRoute = SettingsProfileRouteImport.update({
  id: '/settings/profile',
  path: '/settings/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsNotificationsRoute = SettingsNotificationsRouteImport.update({
  id: '/settings/notifications',
  path: '/settings/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsLanguageRoute = SettingsLanguageRouteImport.update({
  id: '/settings/language',
  path: '/settings/language',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsCompanyAddressesRoute =
  SettingsCompanyAddressesRouteImport.update({
    id: '/settings/company-addresses',
    path: '/settings/company-addresses',
    getParentRoute: () => rootRouteImport,
  } as any)
const SettingsAppearanceRoute = SettingsAppearanceRouteImport.update({
  id: '/settings/appearance',
  path: '/settings/appearance',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsAccountRoute = SettingsAccountRouteImport.update({
  id: '/settings/account',
  path: '/settings/account',
  getParentRoute: () => rootRouteImport,
} as any)
const SalesTestsRoute = SalesTestsRouteImport.update({
  id: '/sales/tests',
  path: '/sales/tests',
  getParentRoute: () => rootRouteImport,
} as any)
const SalesCustomersRoute = SalesCustomersRouteImport.update({
  id: '/sales/customers',
  path: '/sales/customers',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryItemsRoute = InventoryItemsRouteImport.update({
  id: '/inventory/items',
  path: '/inventory/items',
  getParentRoute: () => rootRouteImport,
} as any)
const authLoginRoute = authLoginRouteImport.update({
  id: '/(auth)/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const authChangePasswordRoute = authChangePasswordRouteImport.update({
  id: '/(auth)/change-password',
  path: '/change-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsInventoryIndexRoute = SettingsInventoryIndexRouteImport.update({
  id: '/settings/inventory/',
  path: '/settings/inventory/',
  getParentRoute: () => rootRouteImport,
} as any)
const SalesTestsIndexRoute = SalesTestsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SalesTestsRoute,
} as any)
const SalesCustomersIndexRoute = SalesCustomersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SalesCustomersRoute,
} as any)
const InventoryItemsIndexRoute = InventoryItemsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => InventoryItemsRoute,
} as any)
const SettingsSalesTestTreesRoute = SettingsSalesTestTreesRouteImport.update({
  id: '/settings/sales/test-trees',
  path: '/settings/sales/test-trees',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsSalesTestBasicsRoute = SettingsSalesTestBasicsRouteImport.update({
  id: '/settings/sales/test-basics',
  path: '/settings/sales/test-basics',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsSalesCustomerTypesRoute =
  SettingsSalesCustomerTypesRouteImport.update({
    id: '/settings/sales/customer-types',
    path: '/settings/sales/customer-types',
    getParentRoute: () => rootRouteImport,
  } as any)
const SettingsSalesCustomerGroupsRoute =
  SettingsSalesCustomerGroupsRouteImport.update({
    id: '/settings/sales/customer-groups',
    path: '/settings/sales/customer-groups',
    getParentRoute: () => rootRouteImport,
  } as any)
const SettingsInventoryWarehousesRoute =
  SettingsInventoryWarehousesRouteImport.update({
    id: '/settings/inventory/warehouses',
    path: '/settings/inventory/warehouses',
    getParentRoute: () => rootRouteImport,
  } as any)
const SettingsInventoryUnitsRoute = SettingsInventoryUnitsRouteImport.update({
  id: '/settings/inventory/units',
  path: '/settings/inventory/units',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsInventoryLotsRoute = SettingsInventoryLotsRouteImport.update({
  id: '/settings/inventory/lots',
  path: '/settings/inventory/lots',
  getParentRoute: () => rootRouteImport,
} as any)
const SalesTestsIdRoute = SalesTestsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => SalesTestsRoute,
} as any)
const SalesCustomersIdRoute = SalesCustomersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => SalesCustomersRoute,
} as any)
const InventoryItemsIdRoute = InventoryItemsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => InventoryItemsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/dashboard': typeof DashboardRoute
  '/my-page': typeof MyPageRoute
  '/profile': typeof ProfileRoute
  '/users': typeof UsersRouteWithChildren
  '/change-password': typeof authChangePasswordRoute
  '/login': typeof authLoginRoute
  '/inventory/items': typeof InventoryItemsRouteWithChildren
  '/sales/customers': typeof SalesCustomersRouteWithChildren
  '/sales/tests': typeof SalesTestsRouteWithChildren
  '/settings/account': typeof SettingsAccountRoute
  '/settings/appearance': typeof SettingsAppearanceRoute
  '/settings/company-addresses': typeof SettingsCompanyAddressesRoute
  '/settings/language': typeof SettingsLanguageRoute
  '/settings/notifications': typeof SettingsNotificationsRoute
  '/settings/profile': typeof SettingsProfileRoute
  '/settings/security': typeof SettingsSecurityRoute
  '/users/$id': typeof UsersIdRoute
  '/settings': typeof SettingsIndexRoute
  '/users/': typeof UsersIndexRoute
  '/inventory/items/$id': typeof InventoryItemsIdRoute
  '/sales/customers/$id': typeof SalesCustomersIdRoute
  '/sales/tests/$id': typeof SalesTestsIdRoute
  '/settings/inventory/lots': typeof SettingsInventoryLotsRoute
  '/settings/inventory/units': typeof SettingsInventoryUnitsRoute
  '/settings/inventory/warehouses': typeof SettingsInventoryWarehousesRoute
  '/settings/sales/customer-groups': typeof SettingsSalesCustomerGroupsRoute
  '/settings/sales/customer-types': typeof SettingsSalesCustomerTypesRoute
  '/settings/sales/test-basics': typeof SettingsSalesTestBasicsRoute
  '/settings/sales/test-trees': typeof SettingsSalesTestTreesRoute
  '/inventory/items/': typeof InventoryItemsIndexRoute
  '/sales/customers/': typeof SalesCustomersIndexRoute
  '/sales/tests/': typeof SalesTestsIndexRoute
  '/settings/inventory': typeof SettingsInventoryIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/dashboard': typeof DashboardRoute
  '/my-page': typeof MyPageRoute
  '/profile': typeof ProfileRoute
  '/change-password': typeof authChangePasswordRoute
  '/login': typeof authLoginRoute
  '/settings/account': typeof SettingsAccountRoute
  '/settings/appearance': typeof SettingsAppearanceRoute
  '/settings/company-addresses': typeof SettingsCompanyAddressesRoute
  '/settings/language': typeof SettingsLanguageRoute
  '/settings/notifications': typeof SettingsNotificationsRoute
  '/settings/profile': typeof SettingsProfileRoute
  '/settings/security': typeof SettingsSecurityRoute
  '/users/$id': typeof UsersIdRoute
  '/settings': typeof SettingsIndexRoute
  '/users': typeof UsersIndexRoute
  '/inventory/items/$id': typeof InventoryItemsIdRoute
  '/sales/customers/$id': typeof SalesCustomersIdRoute
  '/sales/tests/$id': typeof SalesTestsIdRoute
  '/settings/inventory/lots': typeof SettingsInventoryLotsRoute
  '/settings/inventory/units': typeof SettingsInventoryUnitsRoute
  '/settings/inventory/warehouses': typeof SettingsInventoryWarehousesRoute
  '/settings/sales/customer-groups': typeof SettingsSalesCustomerGroupsRoute
  '/settings/sales/customer-types': typeof SettingsSalesCustomerTypesRoute
  '/settings/sales/test-basics': typeof SettingsSalesTestBasicsRoute
  '/settings/sales/test-trees': typeof SettingsSalesTestTreesRoute
  '/inventory/items': typeof InventoryItemsIndexRoute
  '/sales/customers': typeof SalesCustomersIndexRoute
  '/sales/tests': typeof SalesTestsIndexRoute
  '/settings/inventory': typeof SettingsInventoryIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/dashboard': typeof DashboardRoute
  '/my-page': typeof MyPageRoute
  '/profile': typeof ProfileRoute
  '/users': typeof UsersRouteWithChildren
  '/(auth)/change-password': typeof authChangePasswordRoute
  '/(auth)/login': typeof authLoginRoute
  '/inventory/items': typeof InventoryItemsRouteWithChildren
  '/sales/customers': typeof SalesCustomersRouteWithChildren
  '/sales/tests': typeof SalesTestsRouteWithChildren
  '/settings/account': typeof SettingsAccountRoute
  '/settings/appearance': typeof SettingsAppearanceRoute
  '/settings/company-addresses': typeof SettingsCompanyAddressesRoute
  '/settings/language': typeof SettingsLanguageRoute
  '/settings/notifications': typeof SettingsNotificationsRoute
  '/settings/profile': typeof SettingsProfileRoute
  '/settings/security': typeof SettingsSecurityRoute
  '/users/$id': typeof UsersIdRoute
  '/settings/': typeof SettingsIndexRoute
  '/users/': typeof UsersIndexRoute
  '/inventory/items/$id': typeof InventoryItemsIdRoute
  '/sales/customers/$id': typeof SalesCustomersIdRoute
  '/sales/tests/$id': typeof SalesTestsIdRoute
  '/settings/inventory/lots': typeof SettingsInventoryLotsRoute
  '/settings/inventory/units': typeof SettingsInventoryUnitsRoute
  '/settings/inventory/warehouses': typeof SettingsInventoryWarehousesRoute
  '/settings/sales/customer-groups': typeof SettingsSalesCustomerGroupsRoute
  '/settings/sales/customer-types': typeof SettingsSalesCustomerTypesRoute
  '/settings/sales/test-basics': typeof SettingsSalesTestBasicsRoute
  '/settings/sales/test-trees': typeof SettingsSalesTestTreesRoute
  '/inventory/items/': typeof InventoryItemsIndexRoute
  '/sales/customers/': typeof SalesCustomersIndexRoute
  '/sales/tests/': typeof SalesTestsIndexRoute
  '/settings/inventory/': typeof SettingsInventoryIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/dashboard'
    | '/my-page'
    | '/profile'
    | '/users'
    | '/change-password'
    | '/login'
    | '/inventory/items'
    | '/sales/customers'
    | '/sales/tests'
    | '/settings/account'
    | '/settings/appearance'
    | '/settings/company-addresses'
    | '/settings/language'
    | '/settings/notifications'
    | '/settings/profile'
    | '/settings/security'
    | '/users/$id'
    | '/settings'
    | '/users/'
    | '/inventory/items/$id'
    | '/sales/customers/$id'
    | '/sales/tests/$id'
    | '/settings/inventory/lots'
    | '/settings/inventory/units'
    | '/settings/inventory/warehouses'
    | '/settings/sales/customer-groups'
    | '/settings/sales/customer-types'
    | '/settings/sales/test-basics'
    | '/settings/sales/test-trees'
    | '/inventory/items/'
    | '/sales/customers/'
    | '/sales/tests/'
    | '/settings/inventory'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/dashboard'
    | '/my-page'
    | '/profile'
    | '/change-password'
    | '/login'
    | '/settings/account'
    | '/settings/appearance'
    | '/settings/company-addresses'
    | '/settings/language'
    | '/settings/notifications'
    | '/settings/profile'
    | '/settings/security'
    | '/users/$id'
    | '/settings'
    | '/users'
    | '/inventory/items/$id'
    | '/sales/customers/$id'
    | '/sales/tests/$id'
    | '/settings/inventory/lots'
    | '/settings/inventory/units'
    | '/settings/inventory/warehouses'
    | '/settings/sales/customer-groups'
    | '/settings/sales/customer-types'
    | '/settings/sales/test-basics'
    | '/settings/sales/test-trees'
    | '/inventory/items'
    | '/sales/customers'
    | '/sales/tests'
    | '/settings/inventory'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/dashboard'
    | '/my-page'
    | '/profile'
    | '/users'
    | '/(auth)/change-password'
    | '/(auth)/login'
    | '/inventory/items'
    | '/sales/customers'
    | '/sales/tests'
    | '/settings/account'
    | '/settings/appearance'
    | '/settings/company-addresses'
    | '/settings/language'
    | '/settings/notifications'
    | '/settings/profile'
    | '/settings/security'
    | '/users/$id'
    | '/settings/'
    | '/users/'
    | '/inventory/items/$id'
    | '/sales/customers/$id'
    | '/sales/tests/$id'
    | '/settings/inventory/lots'
    | '/settings/inventory/units'
    | '/settings/inventory/warehouses'
    | '/settings/sales/customer-groups'
    | '/settings/sales/customer-types'
    | '/settings/sales/test-basics'
    | '/settings/sales/test-trees'
    | '/inventory/items/'
    | '/sales/customers/'
    | '/sales/tests/'
    | '/settings/inventory/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  DashboardRoute: typeof DashboardRoute
  MyPageRoute: typeof MyPageRoute
  ProfileRoute: typeof ProfileRoute
  UsersRoute: typeof UsersRouteWithChildren
  authChangePasswordRoute: typeof authChangePasswordRoute
  authLoginRoute: typeof authLoginRoute
  InventoryItemsRoute: typeof InventoryItemsRouteWithChildren
  SalesCustomersRoute: typeof SalesCustomersRouteWithChildren
  SalesTestsRoute: typeof SalesTestsRouteWithChildren
  SettingsAccountRoute: typeof SettingsAccountRoute
  SettingsAppearanceRoute: typeof SettingsAppearanceRoute
  SettingsCompanyAddressesRoute: typeof SettingsCompanyAddressesRoute
  SettingsLanguageRoute: typeof SettingsLanguageRoute
  SettingsNotificationsRoute: typeof SettingsNotificationsRoute
  SettingsProfileRoute: typeof SettingsProfileRoute
  SettingsSecurityRoute: typeof SettingsSecurityRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
  SettingsInventoryLotsRoute: typeof SettingsInventoryLotsRoute
  SettingsInventoryUnitsRoute: typeof SettingsInventoryUnitsRoute
  SettingsInventoryWarehousesRoute: typeof SettingsInventoryWarehousesRoute
  SettingsSalesCustomerGroupsRoute: typeof SettingsSalesCustomerGroupsRoute
  SettingsSalesCustomerTypesRoute: typeof SettingsSalesCustomerTypesRoute
  SettingsSalesTestBasicsRoute: typeof SettingsSalesTestBasicsRoute
  SettingsSalesTestTreesRoute: typeof SettingsSalesTestTreesRoute
  SettingsInventoryIndexRoute: typeof SettingsInventoryIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-page': {
      id: '/my-page'
      path: '/my-page'
      fullPath: '/my-page'
      preLoaderRoute: typeof MyPageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users/': {
      id: '/users/'
      path: '/'
      fullPath: '/users/'
      preLoaderRoute: typeof UsersIndexRouteImport
      parentRoute: typeof UsersRoute
    }
    '/settings/': {
      id: '/settings/'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users/$id': {
      id: '/users/$id'
      path: '/$id'
      fullPath: '/users/$id'
      preLoaderRoute: typeof UsersIdRouteImport
      parentRoute: typeof UsersRoute
    }
    '/settings/security': {
      id: '/settings/security'
      path: '/settings/security'
      fullPath: '/settings/security'
      preLoaderRoute: typeof SettingsSecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/profile': {
      id: '/settings/profile'
      path: '/settings/profile'
      fullPath: '/settings/profile'
      preLoaderRoute: typeof SettingsProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/notifications': {
      id: '/settings/notifications'
      path: '/settings/notifications'
      fullPath: '/settings/notifications'
      preLoaderRoute: typeof SettingsNotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/language': {
      id: '/settings/language'
      path: '/settings/language'
      fullPath: '/settings/language'
      preLoaderRoute: typeof SettingsLanguageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/company-addresses': {
      id: '/settings/company-addresses'
      path: '/settings/company-addresses'
      fullPath: '/settings/company-addresses'
      preLoaderRoute: typeof SettingsCompanyAddressesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/appearance': {
      id: '/settings/appearance'
      path: '/settings/appearance'
      fullPath: '/settings/appearance'
      preLoaderRoute: typeof SettingsAppearanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/account': {
      id: '/settings/account'
      path: '/settings/account'
      fullPath: '/settings/account'
      preLoaderRoute: typeof SettingsAccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sales/tests': {
      id: '/sales/tests'
      path: '/sales/tests'
      fullPath: '/sales/tests'
      preLoaderRoute: typeof SalesTestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sales/customers': {
      id: '/sales/customers'
      path: '/sales/customers'
      fullPath: '/sales/customers'
      preLoaderRoute: typeof SalesCustomersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory/items': {
      id: '/inventory/items'
      path: '/inventory/items'
      fullPath: '/inventory/items'
      preLoaderRoute: typeof InventoryItemsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/login': {
      id: '/(auth)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/change-password': {
      id: '/(auth)/change-password'
      path: '/change-password'
      fullPath: '/change-password'
      preLoaderRoute: typeof authChangePasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/inventory/': {
      id: '/settings/inventory/'
      path: '/settings/inventory'
      fullPath: '/settings/inventory'
      preLoaderRoute: typeof SettingsInventoryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sales/tests/': {
      id: '/sales/tests/'
      path: '/'
      fullPath: '/sales/tests/'
      preLoaderRoute: typeof SalesTestsIndexRouteImport
      parentRoute: typeof SalesTestsRoute
    }
    '/sales/customers/': {
      id: '/sales/customers/'
      path: '/'
      fullPath: '/sales/customers/'
      preLoaderRoute: typeof SalesCustomersIndexRouteImport
      parentRoute: typeof SalesCustomersRoute
    }
    '/inventory/items/': {
      id: '/inventory/items/'
      path: '/'
      fullPath: '/inventory/items/'
      preLoaderRoute: typeof InventoryItemsIndexRouteImport
      parentRoute: typeof InventoryItemsRoute
    }
    '/settings/sales/test-trees': {
      id: '/settings/sales/test-trees'
      path: '/settings/sales/test-trees'
      fullPath: '/settings/sales/test-trees'
      preLoaderRoute: typeof SettingsSalesTestTreesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/sales/test-basics': {
      id: '/settings/sales/test-basics'
      path: '/settings/sales/test-basics'
      fullPath: '/settings/sales/test-basics'
      preLoaderRoute: typeof SettingsSalesTestBasicsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/sales/customer-types': {
      id: '/settings/sales/customer-types'
      path: '/settings/sales/customer-types'
      fullPath: '/settings/sales/customer-types'
      preLoaderRoute: typeof SettingsSalesCustomerTypesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/sales/customer-groups': {
      id: '/settings/sales/customer-groups'
      path: '/settings/sales/customer-groups'
      fullPath: '/settings/sales/customer-groups'
      preLoaderRoute: typeof SettingsSalesCustomerGroupsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/inventory/warehouses': {
      id: '/settings/inventory/warehouses'
      path: '/settings/inventory/warehouses'
      fullPath: '/settings/inventory/warehouses'
      preLoaderRoute: typeof SettingsInventoryWarehousesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/inventory/units': {
      id: '/settings/inventory/units'
      path: '/settings/inventory/units'
      fullPath: '/settings/inventory/units'
      preLoaderRoute: typeof SettingsInventoryUnitsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/inventory/lots': {
      id: '/settings/inventory/lots'
      path: '/settings/inventory/lots'
      fullPath: '/settings/inventory/lots'
      preLoaderRoute: typeof SettingsInventoryLotsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sales/tests/$id': {
      id: '/sales/tests/$id'
      path: '/$id'
      fullPath: '/sales/tests/$id'
      preLoaderRoute: typeof SalesTestsIdRouteImport
      parentRoute: typeof SalesTestsRoute
    }
    '/sales/customers/$id': {
      id: '/sales/customers/$id'
      path: '/$id'
      fullPath: '/sales/customers/$id'
      preLoaderRoute: typeof SalesCustomersIdRouteImport
      parentRoute: typeof SalesCustomersRoute
    }
    '/inventory/items/$id': {
      id: '/inventory/items/$id'
      path: '/$id'
      fullPath: '/inventory/items/$id'
      preLoaderRoute: typeof InventoryItemsIdRouteImport
      parentRoute: typeof InventoryItemsRoute
    }
  }
}

interface UsersRouteChildren {
  UsersIdRoute: typeof UsersIdRoute
  UsersIndexRoute: typeof UsersIndexRoute
}

const UsersRouteChildren: UsersRouteChildren = {
  UsersIdRoute: UsersIdRoute,
  UsersIndexRoute: UsersIndexRoute,
}

const UsersRouteWithChildren = UsersRoute._addFileChildren(UsersRouteChildren)

interface InventoryItemsRouteChildren {
  InventoryItemsIdRoute: typeof InventoryItemsIdRoute
  InventoryItemsIndexRoute: typeof InventoryItemsIndexRoute
}

const InventoryItemsRouteChildren: InventoryItemsRouteChildren = {
  InventoryItemsIdRoute: InventoryItemsIdRoute,
  InventoryItemsIndexRoute: InventoryItemsIndexRoute,
}

const InventoryItemsRouteWithChildren = InventoryItemsRoute._addFileChildren(
  InventoryItemsRouteChildren,
)

interface SalesCustomersRouteChildren {
  SalesCustomersIdRoute: typeof SalesCustomersIdRoute
  SalesCustomersIndexRoute: typeof SalesCustomersIndexRoute
}

const SalesCustomersRouteChildren: SalesCustomersRouteChildren = {
  SalesCustomersIdRoute: SalesCustomersIdRoute,
  SalesCustomersIndexRoute: SalesCustomersIndexRoute,
}

const SalesCustomersRouteWithChildren = SalesCustomersRoute._addFileChildren(
  SalesCustomersRouteChildren,
)

interface SalesTestsRouteChildren {
  SalesTestsIdRoute: typeof SalesTestsIdRoute
  SalesTestsIndexRoute: typeof SalesTestsIndexRoute
}

const SalesTestsRouteChildren: SalesTestsRouteChildren = {
  SalesTestsIdRoute: SalesTestsIdRoute,
  SalesTestsIndexRoute: SalesTestsIndexRoute,
}

const SalesTestsRouteWithChildren = SalesTestsRoute._addFileChildren(
  SalesTestsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  DashboardRoute: DashboardRoute,
  MyPageRoute: MyPageRoute,
  ProfileRoute: ProfileRoute,
  UsersRoute: UsersRouteWithChildren,
  authChangePasswordRoute: authChangePasswordRoute,
  authLoginRoute: authLoginRoute,
  InventoryItemsRoute: InventoryItemsRouteWithChildren,
  SalesCustomersRoute: SalesCustomersRouteWithChildren,
  SalesTestsRoute: SalesTestsRouteWithChildren,
  SettingsAccountRoute: SettingsAccountRoute,
  SettingsAppearanceRoute: SettingsAppearanceRoute,
  SettingsCompanyAddressesRoute: SettingsCompanyAddressesRoute,
  SettingsLanguageRoute: SettingsLanguageRoute,
  SettingsNotificationsRoute: SettingsNotificationsRoute,
  SettingsProfileRoute: SettingsProfileRoute,
  SettingsSecurityRoute: SettingsSecurityRoute,
  SettingsIndexRoute: SettingsIndexRoute,
  SettingsInventoryLotsRoute: SettingsInventoryLotsRoute,
  SettingsInventoryUnitsRoute: SettingsInventoryUnitsRoute,
  SettingsInventoryWarehousesRoute: SettingsInventoryWarehousesRoute,
  SettingsSalesCustomerGroupsRoute: SettingsSalesCustomerGroupsRoute,
  SettingsSalesCustomerTypesRoute: SettingsSalesCustomerTypesRoute,
  SettingsSalesTestBasicsRoute: SettingsSalesTestBasicsRoute,
  SettingsSalesTestTreesRoute: SettingsSalesTestTreesRoute,
  SettingsInventoryIndexRoute: SettingsInventoryIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
