/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UsersRouteImport } from './routes/users'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as MyPageRouteImport } from './routes/my-page'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as SplatRouteImport } from './routes/$'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UsersIndexRouteImport } from './routes/users/index'
import { Route as SettingsIndexRouteImport } from './routes/settings/index'
import { Route as UsersIdRouteImport } from './routes/users/$id'
import { Route as TicketingVenuesRouteImport } from './routes/ticketing/venues'
import { Route as TicketingShowsRouteImport } from './routes/ticketing/shows'
import { Route as TicketingOrganizersRouteImport } from './routes/ticketing/organizers'
import { Route as SettingsSecurityRouteImport } from './routes/settings/security'
import { Route as SettingsProfileRouteImport } from './routes/settings/profile'
import { Route as SettingsNotificationsRouteImport } from './routes/settings/notifications'
import { Route as SettingsLanguageRouteImport } from './routes/settings/language'
import { Route as SettingsCompanyAddressesRouteImport } from './routes/settings/company-addresses'
import { Route as SettingsAppearanceRouteImport } from './routes/settings/appearance'
import { Route as SettingsAccountRouteImport } from './routes/settings/account'
import { Route as SalesTestsRouteImport } from './routes/sales/tests'
import { Route as SalesPaymentsRouteImport } from './routes/sales/payments'
import { Route as SalesEventsRouteImport } from './routes/sales/events'
import { Route as SalesCustomersRouteImport } from './routes/sales/customers'
import { Route as SalesBookingsRouteImport } from './routes/sales/bookings'
import { Route as authLoginRouteImport } from './routes/(auth)/login'
import { Route as authChangePasswordRouteImport } from './routes/(auth)/change-password'
import { Route as TicketingVenuesIndexRouteImport } from './routes/ticketing/venues/index'
import { Route as TicketingShowsIndexRouteImport } from './routes/ticketing/shows/index'
import { Route as TicketingOrganizersIndexRouteImport } from './routes/ticketing/organizers/index'
import { Route as SalesTestsIndexRouteImport } from './routes/sales/tests/index'
import { Route as SalesPaymentsIndexRouteImport } from './routes/sales/payments/index'
import { Route as SalesEventsIndexRouteImport } from './routes/sales/events/index'
import { Route as SalesCustomersIndexRouteImport } from './routes/sales/customers/index'
import { Route as SalesBookingsIndexRouteImport } from './routes/sales/bookings/index'
import { Route as TicketingVenuesIdRouteImport } from './routes/ticketing/venues/$id'
import { Route as TicketingShowsIdRouteImport } from './routes/ticketing/shows/$id'
import { Route as TicketingOrganizersIdRouteImport } from './routes/ticketing/organizers/$id'
import { Route as SettingsTicketingVenueTypesRouteImport } from './routes/settings/ticketing/venue-types'
import { Route as SettingsTicketingEventTypesRouteImport } from './routes/settings/ticketing/event-types'
import { Route as SettingsSalesTestTreesRouteImport } from './routes/settings/sales/test-trees'
import { Route as SettingsSalesTestBasicsRouteImport } from './routes/settings/sales/test-basics'
import { Route as SettingsSalesCustomerTypesRouteImport } from './routes/settings/sales/customer-types'
import { Route as SettingsSalesCustomerGroupsRouteImport } from './routes/settings/sales/customer-groups'
import { Route as SalesTestsIdRouteImport } from './routes/sales/tests/$id'
import { Route as SalesCustomersIdRouteImport } from './routes/sales/customers/$id'
import { Route as SalesBookingsIdRouteImport } from './routes/sales/bookings/$id'
import { Route as TicketingEventsEventIdInventoryRouteImport } from './routes/ticketing/events/$eventId/inventory'
import { Route as TicketingVenuesIdSeatsDesignerRouteImport } from './routes/ticketing/venues/$id/seats/designer'

const UsersRoute = UsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const MyPageRoute = MyPageRouteImport.update({
  id: '/my-page',
  path: '/my-page',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersIndexRoute = UsersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => UsersRoute,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersIdRoute = UsersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => UsersRoute,
} as any)
const TicketingVenuesRoute = TicketingVenuesRouteImport.update({
  id: '/ticketing/venues',
  path: '/ticketing/venues',
  getParentRoute: () => rootRouteImport,
} as any)
const TicketingShowsRoute = TicketingShowsRouteImport.update({
  id: '/ticketing/shows',
  path: '/ticketing/shows',
  getParentRoute: () => rootRouteImport,
} as any)
const TicketingOrganizersRoute = TicketingOrganizersRouteImport.update({
  id: '/ticketing/organizers',
  path: '/ticketing/organizers',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsSecurityRoute = SettingsSecurityRouteImport.update({
  id: '/settings/security',
  path: '/settings/security',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsProfileRoute = SettingsProfileRouteImport.update({
  id: '/settings/profile',
  path: '/settings/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsNotificationsRoute = SettingsNotificationsRouteImport.update({
  id: '/settings/notifications',
  path: '/settings/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsLanguageRoute = SettingsLanguageRouteImport.update({
  id: '/settings/language',
  path: '/settings/language',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsCompanyAddressesRoute =
  SettingsCompanyAddressesRouteImport.update({
    id: '/settings/company-addresses',
    path: '/settings/company-addresses',
    getParentRoute: () => rootRouteImport,
  } as any)
const SettingsAppearanceRoute = SettingsAppearanceRouteImport.update({
  id: '/settings/appearance',
  path: '/settings/appearance',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsAccountRoute = SettingsAccountRouteImport.update({
  id: '/settings/account',
  path: '/settings/account',
  getParentRoute: () => rootRouteImport,
} as any)
const SalesTestsRoute = SalesTestsRouteImport.update({
  id: '/sales/tests',
  path: '/sales/tests',
  getParentRoute: () => rootRouteImport,
} as any)
const SalesPaymentsRoute = SalesPaymentsRouteImport.update({
  id: '/sales/payments',
  path: '/sales/payments',
  getParentRoute: () => rootRouteImport,
} as any)
const SalesEventsRoute = SalesEventsRouteImport.update({
  id: '/sales/events',
  path: '/sales/events',
  getParentRoute: () => rootRouteImport,
} as any)
const SalesCustomersRoute = SalesCustomersRouteImport.update({
  id: '/sales/customers',
  path: '/sales/customers',
  getParentRoute: () => rootRouteImport,
} as any)
const SalesBookingsRoute = SalesBookingsRouteImport.update({
  id: '/sales/bookings',
  path: '/sales/bookings',
  getParentRoute: () => rootRouteImport,
} as any)
const authLoginRoute = authLoginRouteImport.update({
  id: '/(auth)/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const authChangePasswordRoute = authChangePasswordRouteImport.update({
  id: '/(auth)/change-password',
  path: '/change-password',
  getParentRoute: () => rootRouteImport,
} as any)
const TicketingVenuesIndexRoute = TicketingVenuesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TicketingVenuesRoute,
} as any)
const TicketingShowsIndexRoute = TicketingShowsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TicketingShowsRoute,
} as any)
const TicketingOrganizersIndexRoute =
  TicketingOrganizersIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => TicketingOrganizersRoute,
  } as any)
const SalesTestsIndexRoute = SalesTestsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SalesTestsRoute,
} as any)
const SalesPaymentsIndexRoute = SalesPaymentsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SalesPaymentsRoute,
} as any)
const SalesEventsIndexRoute = SalesEventsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SalesEventsRoute,
} as any)
const SalesCustomersIndexRoute = SalesCustomersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SalesCustomersRoute,
} as any)
const SalesBookingsIndexRoute = SalesBookingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SalesBookingsRoute,
} as any)
const TicketingVenuesIdRoute = TicketingVenuesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => TicketingVenuesRoute,
} as any)
const TicketingShowsIdRoute = TicketingShowsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => TicketingShowsRoute,
} as any)
const TicketingOrganizersIdRoute = TicketingOrganizersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => TicketingOrganizersRoute,
} as any)
const SettingsTicketingVenueTypesRoute =
  SettingsTicketingVenueTypesRouteImport.update({
    id: '/settings/ticketing/venue-types',
    path: '/settings/ticketing/venue-types',
    getParentRoute: () => rootRouteImport,
  } as any)
const SettingsTicketingEventTypesRoute =
  SettingsTicketingEventTypesRouteImport.update({
    id: '/settings/ticketing/event-types',
    path: '/settings/ticketing/event-types',
    getParentRoute: () => rootRouteImport,
  } as any)
const SettingsSalesTestTreesRoute = SettingsSalesTestTreesRouteImport.update({
  id: '/settings/sales/test-trees',
  path: '/settings/sales/test-trees',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsSalesTestBasicsRoute = SettingsSalesTestBasicsRouteImport.update({
  id: '/settings/sales/test-basics',
  path: '/settings/sales/test-basics',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsSalesCustomerTypesRoute =
  SettingsSalesCustomerTypesRouteImport.update({
    id: '/settings/sales/customer-types',
    path: '/settings/sales/customer-types',
    getParentRoute: () => rootRouteImport,
  } as any)
const SettingsSalesCustomerGroupsRoute =
  SettingsSalesCustomerGroupsRouteImport.update({
    id: '/settings/sales/customer-groups',
    path: '/settings/sales/customer-groups',
    getParentRoute: () => rootRouteImport,
  } as any)
const SalesTestsIdRoute = SalesTestsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => SalesTestsRoute,
} as any)
const SalesCustomersIdRoute = SalesCustomersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => SalesCustomersRoute,
} as any)
const SalesBookingsIdRoute = SalesBookingsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => SalesBookingsRoute,
} as any)
const TicketingEventsEventIdInventoryRoute =
  TicketingEventsEventIdInventoryRouteImport.update({
    id: '/ticketing/events/$eventId/inventory',
    path: '/ticketing/events/$eventId/inventory',
    getParentRoute: () => rootRouteImport,
  } as any)
const TicketingVenuesIdSeatsDesignerRoute =
  TicketingVenuesIdSeatsDesignerRouteImport.update({
    id: '/seats/designer',
    path: '/seats/designer',
    getParentRoute: () => TicketingVenuesIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/dashboard': typeof DashboardRoute
  '/my-page': typeof MyPageRoute
  '/profile': typeof ProfileRoute
  '/users': typeof UsersRouteWithChildren
  '/change-password': typeof authChangePasswordRoute
  '/login': typeof authLoginRoute
  '/sales/bookings': typeof SalesBookingsRouteWithChildren
  '/sales/customers': typeof SalesCustomersRouteWithChildren
  '/sales/events': typeof SalesEventsRouteWithChildren
  '/sales/payments': typeof SalesPaymentsRouteWithChildren
  '/sales/tests': typeof SalesTestsRouteWithChildren
  '/settings/account': typeof SettingsAccountRoute
  '/settings/appearance': typeof SettingsAppearanceRoute
  '/settings/company-addresses': typeof SettingsCompanyAddressesRoute
  '/settings/language': typeof SettingsLanguageRoute
  '/settings/notifications': typeof SettingsNotificationsRoute
  '/settings/profile': typeof SettingsProfileRoute
  '/settings/security': typeof SettingsSecurityRoute
  '/ticketing/organizers': typeof TicketingOrganizersRouteWithChildren
  '/ticketing/shows': typeof TicketingShowsRouteWithChildren
  '/ticketing/venues': typeof TicketingVenuesRouteWithChildren
  '/users/$id': typeof UsersIdRoute
  '/settings': typeof SettingsIndexRoute
  '/users/': typeof UsersIndexRoute
  '/sales/bookings/$id': typeof SalesBookingsIdRoute
  '/sales/customers/$id': typeof SalesCustomersIdRoute
  '/sales/tests/$id': typeof SalesTestsIdRoute
  '/settings/sales/customer-groups': typeof SettingsSalesCustomerGroupsRoute
  '/settings/sales/customer-types': typeof SettingsSalesCustomerTypesRoute
  '/settings/sales/test-basics': typeof SettingsSalesTestBasicsRoute
  '/settings/sales/test-trees': typeof SettingsSalesTestTreesRoute
  '/settings/ticketing/event-types': typeof SettingsTicketingEventTypesRoute
  '/settings/ticketing/venue-types': typeof SettingsTicketingVenueTypesRoute
  '/ticketing/organizers/$id': typeof TicketingOrganizersIdRoute
  '/ticketing/shows/$id': typeof TicketingShowsIdRoute
  '/ticketing/venues/$id': typeof TicketingVenuesIdRouteWithChildren
  '/sales/bookings/': typeof SalesBookingsIndexRoute
  '/sales/customers/': typeof SalesCustomersIndexRoute
  '/sales/events/': typeof SalesEventsIndexRoute
  '/sales/payments/': typeof SalesPaymentsIndexRoute
  '/sales/tests/': typeof SalesTestsIndexRoute
  '/ticketing/organizers/': typeof TicketingOrganizersIndexRoute
  '/ticketing/shows/': typeof TicketingShowsIndexRoute
  '/ticketing/venues/': typeof TicketingVenuesIndexRoute
  '/ticketing/events/$eventId/inventory': typeof TicketingEventsEventIdInventoryRoute
  '/ticketing/venues/$id/seats/designer': typeof TicketingVenuesIdSeatsDesignerRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/dashboard': typeof DashboardRoute
  '/my-page': typeof MyPageRoute
  '/profile': typeof ProfileRoute
  '/change-password': typeof authChangePasswordRoute
  '/login': typeof authLoginRoute
  '/settings/account': typeof SettingsAccountRoute
  '/settings/appearance': typeof SettingsAppearanceRoute
  '/settings/company-addresses': typeof SettingsCompanyAddressesRoute
  '/settings/language': typeof SettingsLanguageRoute
  '/settings/notifications': typeof SettingsNotificationsRoute
  '/settings/profile': typeof SettingsProfileRoute
  '/settings/security': typeof SettingsSecurityRoute
  '/users/$id': typeof UsersIdRoute
  '/settings': typeof SettingsIndexRoute
  '/users': typeof UsersIndexRoute
  '/sales/bookings/$id': typeof SalesBookingsIdRoute
  '/sales/customers/$id': typeof SalesCustomersIdRoute
  '/sales/tests/$id': typeof SalesTestsIdRoute
  '/settings/sales/customer-groups': typeof SettingsSalesCustomerGroupsRoute
  '/settings/sales/customer-types': typeof SettingsSalesCustomerTypesRoute
  '/settings/sales/test-basics': typeof SettingsSalesTestBasicsRoute
  '/settings/sales/test-trees': typeof SettingsSalesTestTreesRoute
  '/settings/ticketing/event-types': typeof SettingsTicketingEventTypesRoute
  '/settings/ticketing/venue-types': typeof SettingsTicketingVenueTypesRoute
  '/ticketing/organizers/$id': typeof TicketingOrganizersIdRoute
  '/ticketing/shows/$id': typeof TicketingShowsIdRoute
  '/ticketing/venues/$id': typeof TicketingVenuesIdRouteWithChildren
  '/sales/bookings': typeof SalesBookingsIndexRoute
  '/sales/customers': typeof SalesCustomersIndexRoute
  '/sales/events': typeof SalesEventsIndexRoute
  '/sales/payments': typeof SalesPaymentsIndexRoute
  '/sales/tests': typeof SalesTestsIndexRoute
  '/ticketing/organizers': typeof TicketingOrganizersIndexRoute
  '/ticketing/shows': typeof TicketingShowsIndexRoute
  '/ticketing/venues': typeof TicketingVenuesIndexRoute
  '/ticketing/events/$eventId/inventory': typeof TicketingEventsEventIdInventoryRoute
  '/ticketing/venues/$id/seats/designer': typeof TicketingVenuesIdSeatsDesignerRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/dashboard': typeof DashboardRoute
  '/my-page': typeof MyPageRoute
  '/profile': typeof ProfileRoute
  '/users': typeof UsersRouteWithChildren
  '/(auth)/change-password': typeof authChangePasswordRoute
  '/(auth)/login': typeof authLoginRoute
  '/sales/bookings': typeof SalesBookingsRouteWithChildren
  '/sales/customers': typeof SalesCustomersRouteWithChildren
  '/sales/events': typeof SalesEventsRouteWithChildren
  '/sales/payments': typeof SalesPaymentsRouteWithChildren
  '/sales/tests': typeof SalesTestsRouteWithChildren
  '/settings/account': typeof SettingsAccountRoute
  '/settings/appearance': typeof SettingsAppearanceRoute
  '/settings/company-addresses': typeof SettingsCompanyAddressesRoute
  '/settings/language': typeof SettingsLanguageRoute
  '/settings/notifications': typeof SettingsNotificationsRoute
  '/settings/profile': typeof SettingsProfileRoute
  '/settings/security': typeof SettingsSecurityRoute
  '/ticketing/organizers': typeof TicketingOrganizersRouteWithChildren
  '/ticketing/shows': typeof TicketingShowsRouteWithChildren
  '/ticketing/venues': typeof TicketingVenuesRouteWithChildren
  '/users/$id': typeof UsersIdRoute
  '/settings/': typeof SettingsIndexRoute
  '/users/': typeof UsersIndexRoute
  '/sales/bookings/$id': typeof SalesBookingsIdRoute
  '/sales/customers/$id': typeof SalesCustomersIdRoute
  '/sales/tests/$id': typeof SalesTestsIdRoute
  '/settings/sales/customer-groups': typeof SettingsSalesCustomerGroupsRoute
  '/settings/sales/customer-types': typeof SettingsSalesCustomerTypesRoute
  '/settings/sales/test-basics': typeof SettingsSalesTestBasicsRoute
  '/settings/sales/test-trees': typeof SettingsSalesTestTreesRoute
  '/settings/ticketing/event-types': typeof SettingsTicketingEventTypesRoute
  '/settings/ticketing/venue-types': typeof SettingsTicketingVenueTypesRoute
  '/ticketing/organizers/$id': typeof TicketingOrganizersIdRoute
  '/ticketing/shows/$id': typeof TicketingShowsIdRoute
  '/ticketing/venues/$id': typeof TicketingVenuesIdRouteWithChildren
  '/sales/bookings/': typeof SalesBookingsIndexRoute
  '/sales/customers/': typeof SalesCustomersIndexRoute
  '/sales/events/': typeof SalesEventsIndexRoute
  '/sales/payments/': typeof SalesPaymentsIndexRoute
  '/sales/tests/': typeof SalesTestsIndexRoute
  '/ticketing/organizers/': typeof TicketingOrganizersIndexRoute
  '/ticketing/shows/': typeof TicketingShowsIndexRoute
  '/ticketing/venues/': typeof TicketingVenuesIndexRoute
  '/ticketing/events/$eventId/inventory': typeof TicketingEventsEventIdInventoryRoute
  '/ticketing/venues/$id/seats/designer': typeof TicketingVenuesIdSeatsDesignerRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/dashboard'
    | '/my-page'
    | '/profile'
    | '/users'
    | '/change-password'
    | '/login'
    | '/sales/bookings'
    | '/sales/customers'
    | '/sales/events'
    | '/sales/payments'
    | '/sales/tests'
    | '/settings/account'
    | '/settings/appearance'
    | '/settings/company-addresses'
    | '/settings/language'
    | '/settings/notifications'
    | '/settings/profile'
    | '/settings/security'
    | '/ticketing/organizers'
    | '/ticketing/shows'
    | '/ticketing/venues'
    | '/users/$id'
    | '/settings'
    | '/users/'
    | '/sales/bookings/$id'
    | '/sales/customers/$id'
    | '/sales/tests/$id'
    | '/settings/sales/customer-groups'
    | '/settings/sales/customer-types'
    | '/settings/sales/test-basics'
    | '/settings/sales/test-trees'
    | '/settings/ticketing/event-types'
    | '/settings/ticketing/venue-types'
    | '/ticketing/organizers/$id'
    | '/ticketing/shows/$id'
    | '/ticketing/venues/$id'
    | '/sales/bookings/'
    | '/sales/customers/'
    | '/sales/events/'
    | '/sales/payments/'
    | '/sales/tests/'
    | '/ticketing/organizers/'
    | '/ticketing/shows/'
    | '/ticketing/venues/'
    | '/ticketing/events/$eventId/inventory'
    | '/ticketing/venues/$id/seats/designer'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/dashboard'
    | '/my-page'
    | '/profile'
    | '/change-password'
    | '/login'
    | '/settings/account'
    | '/settings/appearance'
    | '/settings/company-addresses'
    | '/settings/language'
    | '/settings/notifications'
    | '/settings/profile'
    | '/settings/security'
    | '/users/$id'
    | '/settings'
    | '/users'
    | '/sales/bookings/$id'
    | '/sales/customers/$id'
    | '/sales/tests/$id'
    | '/settings/sales/customer-groups'
    | '/settings/sales/customer-types'
    | '/settings/sales/test-basics'
    | '/settings/sales/test-trees'
    | '/settings/ticketing/event-types'
    | '/settings/ticketing/venue-types'
    | '/ticketing/organizers/$id'
    | '/ticketing/shows/$id'
    | '/ticketing/venues/$id'
    | '/sales/bookings'
    | '/sales/customers'
    | '/sales/events'
    | '/sales/payments'
    | '/sales/tests'
    | '/ticketing/organizers'
    | '/ticketing/shows'
    | '/ticketing/venues'
    | '/ticketing/events/$eventId/inventory'
    | '/ticketing/venues/$id/seats/designer'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/dashboard'
    | '/my-page'
    | '/profile'
    | '/users'
    | '/(auth)/change-password'
    | '/(auth)/login'
    | '/sales/bookings'
    | '/sales/customers'
    | '/sales/events'
    | '/sales/payments'
    | '/sales/tests'
    | '/settings/account'
    | '/settings/appearance'
    | '/settings/company-addresses'
    | '/settings/language'
    | '/settings/notifications'
    | '/settings/profile'
    | '/settings/security'
    | '/ticketing/organizers'
    | '/ticketing/shows'
    | '/ticketing/venues'
    | '/users/$id'
    | '/settings/'
    | '/users/'
    | '/sales/bookings/$id'
    | '/sales/customers/$id'
    | '/sales/tests/$id'
    | '/settings/sales/customer-groups'
    | '/settings/sales/customer-types'
    | '/settings/sales/test-basics'
    | '/settings/sales/test-trees'
    | '/settings/ticketing/event-types'
    | '/settings/ticketing/venue-types'
    | '/ticketing/organizers/$id'
    | '/ticketing/shows/$id'
    | '/ticketing/venues/$id'
    | '/sales/bookings/'
    | '/sales/customers/'
    | '/sales/events/'
    | '/sales/payments/'
    | '/sales/tests/'
    | '/ticketing/organizers/'
    | '/ticketing/shows/'
    | '/ticketing/venues/'
    | '/ticketing/events/$eventId/inventory'
    | '/ticketing/venues/$id/seats/designer'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  DashboardRoute: typeof DashboardRoute
  MyPageRoute: typeof MyPageRoute
  ProfileRoute: typeof ProfileRoute
  UsersRoute: typeof UsersRouteWithChildren
  authChangePasswordRoute: typeof authChangePasswordRoute
  authLoginRoute: typeof authLoginRoute
  SalesBookingsRoute: typeof SalesBookingsRouteWithChildren
  SalesCustomersRoute: typeof SalesCustomersRouteWithChildren
  SalesEventsRoute: typeof SalesEventsRouteWithChildren
  SalesPaymentsRoute: typeof SalesPaymentsRouteWithChildren
  SalesTestsRoute: typeof SalesTestsRouteWithChildren
  SettingsAccountRoute: typeof SettingsAccountRoute
  SettingsAppearanceRoute: typeof SettingsAppearanceRoute
  SettingsCompanyAddressesRoute: typeof SettingsCompanyAddressesRoute
  SettingsLanguageRoute: typeof SettingsLanguageRoute
  SettingsNotificationsRoute: typeof SettingsNotificationsRoute
  SettingsProfileRoute: typeof SettingsProfileRoute
  SettingsSecurityRoute: typeof SettingsSecurityRoute
  TicketingOrganizersRoute: typeof TicketingOrganizersRouteWithChildren
  TicketingShowsRoute: typeof TicketingShowsRouteWithChildren
  TicketingVenuesRoute: typeof TicketingVenuesRouteWithChildren
  SettingsIndexRoute: typeof SettingsIndexRoute
  SettingsSalesCustomerGroupsRoute: typeof SettingsSalesCustomerGroupsRoute
  SettingsSalesCustomerTypesRoute: typeof SettingsSalesCustomerTypesRoute
  SettingsSalesTestBasicsRoute: typeof SettingsSalesTestBasicsRoute
  SettingsSalesTestTreesRoute: typeof SettingsSalesTestTreesRoute
  SettingsTicketingEventTypesRoute: typeof SettingsTicketingEventTypesRoute
  SettingsTicketingVenueTypesRoute: typeof SettingsTicketingVenueTypesRoute
  TicketingEventsEventIdInventoryRoute: typeof TicketingEventsEventIdInventoryRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-page': {
      id: '/my-page'
      path: '/my-page'
      fullPath: '/my-page'
      preLoaderRoute: typeof MyPageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users/': {
      id: '/users/'
      path: '/'
      fullPath: '/users/'
      preLoaderRoute: typeof UsersIndexRouteImport
      parentRoute: typeof UsersRoute
    }
    '/settings/': {
      id: '/settings/'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users/$id': {
      id: '/users/$id'
      path: '/$id'
      fullPath: '/users/$id'
      preLoaderRoute: typeof UsersIdRouteImport
      parentRoute: typeof UsersRoute
    }
    '/ticketing/venues': {
      id: '/ticketing/venues'
      path: '/ticketing/venues'
      fullPath: '/ticketing/venues'
      preLoaderRoute: typeof TicketingVenuesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ticketing/shows': {
      id: '/ticketing/shows'
      path: '/ticketing/shows'
      fullPath: '/ticketing/shows'
      preLoaderRoute: typeof TicketingShowsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ticketing/organizers': {
      id: '/ticketing/organizers'
      path: '/ticketing/organizers'
      fullPath: '/ticketing/organizers'
      preLoaderRoute: typeof TicketingOrganizersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/security': {
      id: '/settings/security'
      path: '/settings/security'
      fullPath: '/settings/security'
      preLoaderRoute: typeof SettingsSecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/profile': {
      id: '/settings/profile'
      path: '/settings/profile'
      fullPath: '/settings/profile'
      preLoaderRoute: typeof SettingsProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/notifications': {
      id: '/settings/notifications'
      path: '/settings/notifications'
      fullPath: '/settings/notifications'
      preLoaderRoute: typeof SettingsNotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/language': {
      id: '/settings/language'
      path: '/settings/language'
      fullPath: '/settings/language'
      preLoaderRoute: typeof SettingsLanguageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/company-addresses': {
      id: '/settings/company-addresses'
      path: '/settings/company-addresses'
      fullPath: '/settings/company-addresses'
      preLoaderRoute: typeof SettingsCompanyAddressesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/appearance': {
      id: '/settings/appearance'
      path: '/settings/appearance'
      fullPath: '/settings/appearance'
      preLoaderRoute: typeof SettingsAppearanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/account': {
      id: '/settings/account'
      path: '/settings/account'
      fullPath: '/settings/account'
      preLoaderRoute: typeof SettingsAccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sales/tests': {
      id: '/sales/tests'
      path: '/sales/tests'
      fullPath: '/sales/tests'
      preLoaderRoute: typeof SalesTestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sales/payments': {
      id: '/sales/payments'
      path: '/sales/payments'
      fullPath: '/sales/payments'
      preLoaderRoute: typeof SalesPaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sales/events': {
      id: '/sales/events'
      path: '/sales/events'
      fullPath: '/sales/events'
      preLoaderRoute: typeof SalesEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sales/customers': {
      id: '/sales/customers'
      path: '/sales/customers'
      fullPath: '/sales/customers'
      preLoaderRoute: typeof SalesCustomersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sales/bookings': {
      id: '/sales/bookings'
      path: '/sales/bookings'
      fullPath: '/sales/bookings'
      preLoaderRoute: typeof SalesBookingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/login': {
      id: '/(auth)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/change-password': {
      id: '/(auth)/change-password'
      path: '/change-password'
      fullPath: '/change-password'
      preLoaderRoute: typeof authChangePasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ticketing/venues/': {
      id: '/ticketing/venues/'
      path: '/'
      fullPath: '/ticketing/venues/'
      preLoaderRoute: typeof TicketingVenuesIndexRouteImport
      parentRoute: typeof TicketingVenuesRoute
    }
    '/ticketing/shows/': {
      id: '/ticketing/shows/'
      path: '/'
      fullPath: '/ticketing/shows/'
      preLoaderRoute: typeof TicketingShowsIndexRouteImport
      parentRoute: typeof TicketingShowsRoute
    }
    '/ticketing/organizers/': {
      id: '/ticketing/organizers/'
      path: '/'
      fullPath: '/ticketing/organizers/'
      preLoaderRoute: typeof TicketingOrganizersIndexRouteImport
      parentRoute: typeof TicketingOrganizersRoute
    }
    '/sales/tests/': {
      id: '/sales/tests/'
      path: '/'
      fullPath: '/sales/tests/'
      preLoaderRoute: typeof SalesTestsIndexRouteImport
      parentRoute: typeof SalesTestsRoute
    }
    '/sales/payments/': {
      id: '/sales/payments/'
      path: '/'
      fullPath: '/sales/payments/'
      preLoaderRoute: typeof SalesPaymentsIndexRouteImport
      parentRoute: typeof SalesPaymentsRoute
    }
    '/sales/events/': {
      id: '/sales/events/'
      path: '/'
      fullPath: '/sales/events/'
      preLoaderRoute: typeof SalesEventsIndexRouteImport
      parentRoute: typeof SalesEventsRoute
    }
    '/sales/customers/': {
      id: '/sales/customers/'
      path: '/'
      fullPath: '/sales/customers/'
      preLoaderRoute: typeof SalesCustomersIndexRouteImport
      parentRoute: typeof SalesCustomersRoute
    }
    '/sales/bookings/': {
      id: '/sales/bookings/'
      path: '/'
      fullPath: '/sales/bookings/'
      preLoaderRoute: typeof SalesBookingsIndexRouteImport
      parentRoute: typeof SalesBookingsRoute
    }
    '/ticketing/venues/$id': {
      id: '/ticketing/venues/$id'
      path: '/$id'
      fullPath: '/ticketing/venues/$id'
      preLoaderRoute: typeof TicketingVenuesIdRouteImport
      parentRoute: typeof TicketingVenuesRoute
    }
    '/ticketing/shows/$id': {
      id: '/ticketing/shows/$id'
      path: '/$id'
      fullPath: '/ticketing/shows/$id'
      preLoaderRoute: typeof TicketingShowsIdRouteImport
      parentRoute: typeof TicketingShowsRoute
    }
    '/ticketing/organizers/$id': {
      id: '/ticketing/organizers/$id'
      path: '/$id'
      fullPath: '/ticketing/organizers/$id'
      preLoaderRoute: typeof TicketingOrganizersIdRouteImport
      parentRoute: typeof TicketingOrganizersRoute
    }
    '/settings/ticketing/venue-types': {
      id: '/settings/ticketing/venue-types'
      path: '/settings/ticketing/venue-types'
      fullPath: '/settings/ticketing/venue-types'
      preLoaderRoute: typeof SettingsTicketingVenueTypesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/ticketing/event-types': {
      id: '/settings/ticketing/event-types'
      path: '/settings/ticketing/event-types'
      fullPath: '/settings/ticketing/event-types'
      preLoaderRoute: typeof SettingsTicketingEventTypesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/sales/test-trees': {
      id: '/settings/sales/test-trees'
      path: '/settings/sales/test-trees'
      fullPath: '/settings/sales/test-trees'
      preLoaderRoute: typeof SettingsSalesTestTreesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/sales/test-basics': {
      id: '/settings/sales/test-basics'
      path: '/settings/sales/test-basics'
      fullPath: '/settings/sales/test-basics'
      preLoaderRoute: typeof SettingsSalesTestBasicsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/sales/customer-types': {
      id: '/settings/sales/customer-types'
      path: '/settings/sales/customer-types'
      fullPath: '/settings/sales/customer-types'
      preLoaderRoute: typeof SettingsSalesCustomerTypesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/sales/customer-groups': {
      id: '/settings/sales/customer-groups'
      path: '/settings/sales/customer-groups'
      fullPath: '/settings/sales/customer-groups'
      preLoaderRoute: typeof SettingsSalesCustomerGroupsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sales/tests/$id': {
      id: '/sales/tests/$id'
      path: '/$id'
      fullPath: '/sales/tests/$id'
      preLoaderRoute: typeof SalesTestsIdRouteImport
      parentRoute: typeof SalesTestsRoute
    }
    '/sales/customers/$id': {
      id: '/sales/customers/$id'
      path: '/$id'
      fullPath: '/sales/customers/$id'
      preLoaderRoute: typeof SalesCustomersIdRouteImport
      parentRoute: typeof SalesCustomersRoute
    }
    '/sales/bookings/$id': {
      id: '/sales/bookings/$id'
      path: '/$id'
      fullPath: '/sales/bookings/$id'
      preLoaderRoute: typeof SalesBookingsIdRouteImport
      parentRoute: typeof SalesBookingsRoute
    }
    '/ticketing/events/$eventId/inventory': {
      id: '/ticketing/events/$eventId/inventory'
      path: '/ticketing/events/$eventId/inventory'
      fullPath: '/ticketing/events/$eventId/inventory'
      preLoaderRoute: typeof TicketingEventsEventIdInventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ticketing/venues/$id/seats/designer': {
      id: '/ticketing/venues/$id/seats/designer'
      path: '/seats/designer'
      fullPath: '/ticketing/venues/$id/seats/designer'
      preLoaderRoute: typeof TicketingVenuesIdSeatsDesignerRouteImport
      parentRoute: typeof TicketingVenuesIdRoute
    }
  }
}

interface UsersRouteChildren {
  UsersIdRoute: typeof UsersIdRoute
  UsersIndexRoute: typeof UsersIndexRoute
}

const UsersRouteChildren: UsersRouteChildren = {
  UsersIdRoute: UsersIdRoute,
  UsersIndexRoute: UsersIndexRoute,
}

const UsersRouteWithChildren = UsersRoute._addFileChildren(UsersRouteChildren)

interface SalesBookingsRouteChildren {
  SalesBookingsIdRoute: typeof SalesBookingsIdRoute
  SalesBookingsIndexRoute: typeof SalesBookingsIndexRoute
}

const SalesBookingsRouteChildren: SalesBookingsRouteChildren = {
  SalesBookingsIdRoute: SalesBookingsIdRoute,
  SalesBookingsIndexRoute: SalesBookingsIndexRoute,
}

const SalesBookingsRouteWithChildren = SalesBookingsRoute._addFileChildren(
  SalesBookingsRouteChildren,
)

interface SalesCustomersRouteChildren {
  SalesCustomersIdRoute: typeof SalesCustomersIdRoute
  SalesCustomersIndexRoute: typeof SalesCustomersIndexRoute
}

const SalesCustomersRouteChildren: SalesCustomersRouteChildren = {
  SalesCustomersIdRoute: SalesCustomersIdRoute,
  SalesCustomersIndexRoute: SalesCustomersIndexRoute,
}

const SalesCustomersRouteWithChildren = SalesCustomersRoute._addFileChildren(
  SalesCustomersRouteChildren,
)

interface SalesEventsRouteChildren {
  SalesEventsIndexRoute: typeof SalesEventsIndexRoute
}

const SalesEventsRouteChildren: SalesEventsRouteChildren = {
  SalesEventsIndexRoute: SalesEventsIndexRoute,
}

const SalesEventsRouteWithChildren = SalesEventsRoute._addFileChildren(
  SalesEventsRouteChildren,
)

interface SalesPaymentsRouteChildren {
  SalesPaymentsIndexRoute: typeof SalesPaymentsIndexRoute
}

const SalesPaymentsRouteChildren: SalesPaymentsRouteChildren = {
  SalesPaymentsIndexRoute: SalesPaymentsIndexRoute,
}

const SalesPaymentsRouteWithChildren = SalesPaymentsRoute._addFileChildren(
  SalesPaymentsRouteChildren,
)

interface SalesTestsRouteChildren {
  SalesTestsIdRoute: typeof SalesTestsIdRoute
  SalesTestsIndexRoute: typeof SalesTestsIndexRoute
}

const SalesTestsRouteChildren: SalesTestsRouteChildren = {
  SalesTestsIdRoute: SalesTestsIdRoute,
  SalesTestsIndexRoute: SalesTestsIndexRoute,
}

const SalesTestsRouteWithChildren = SalesTestsRoute._addFileChildren(
  SalesTestsRouteChildren,
)

interface TicketingOrganizersRouteChildren {
  TicketingOrganizersIdRoute: typeof TicketingOrganizersIdRoute
  TicketingOrganizersIndexRoute: typeof TicketingOrganizersIndexRoute
}

const TicketingOrganizersRouteChildren: TicketingOrganizersRouteChildren = {
  TicketingOrganizersIdRoute: TicketingOrganizersIdRoute,
  TicketingOrganizersIndexRoute: TicketingOrganizersIndexRoute,
}

const TicketingOrganizersRouteWithChildren =
  TicketingOrganizersRoute._addFileChildren(TicketingOrganizersRouteChildren)

interface TicketingShowsRouteChildren {
  TicketingShowsIdRoute: typeof TicketingShowsIdRoute
  TicketingShowsIndexRoute: typeof TicketingShowsIndexRoute
}

const TicketingShowsRouteChildren: TicketingShowsRouteChildren = {
  TicketingShowsIdRoute: TicketingShowsIdRoute,
  TicketingShowsIndexRoute: TicketingShowsIndexRoute,
}

const TicketingShowsRouteWithChildren = TicketingShowsRoute._addFileChildren(
  TicketingShowsRouteChildren,
)

interface TicketingVenuesIdRouteChildren {
  TicketingVenuesIdSeatsDesignerRoute: typeof TicketingVenuesIdSeatsDesignerRoute
}

const TicketingVenuesIdRouteChildren: TicketingVenuesIdRouteChildren = {
  TicketingVenuesIdSeatsDesignerRoute: TicketingVenuesIdSeatsDesignerRoute,
}

const TicketingVenuesIdRouteWithChildren =
  TicketingVenuesIdRoute._addFileChildren(TicketingVenuesIdRouteChildren)

interface TicketingVenuesRouteChildren {
  TicketingVenuesIdRoute: typeof TicketingVenuesIdRouteWithChildren
  TicketingVenuesIndexRoute: typeof TicketingVenuesIndexRoute
}

const TicketingVenuesRouteChildren: TicketingVenuesRouteChildren = {
  TicketingVenuesIdRoute: TicketingVenuesIdRouteWithChildren,
  TicketingVenuesIndexRoute: TicketingVenuesIndexRoute,
}

const TicketingVenuesRouteWithChildren = TicketingVenuesRoute._addFileChildren(
  TicketingVenuesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  DashboardRoute: DashboardRoute,
  MyPageRoute: MyPageRoute,
  ProfileRoute: ProfileRoute,
  UsersRoute: UsersRouteWithChildren,
  authChangePasswordRoute: authChangePasswordRoute,
  authLoginRoute: authLoginRoute,
  SalesBookingsRoute: SalesBookingsRouteWithChildren,
  SalesCustomersRoute: SalesCustomersRouteWithChildren,
  SalesEventsRoute: SalesEventsRouteWithChildren,
  SalesPaymentsRoute: SalesPaymentsRouteWithChildren,
  SalesTestsRoute: SalesTestsRouteWithChildren,
  SettingsAccountRoute: SettingsAccountRoute,
  SettingsAppearanceRoute: SettingsAppearanceRoute,
  SettingsCompanyAddressesRoute: SettingsCompanyAddressesRoute,
  SettingsLanguageRoute: SettingsLanguageRoute,
  SettingsNotificationsRoute: SettingsNotificationsRoute,
  SettingsProfileRoute: SettingsProfileRoute,
  SettingsSecurityRoute: SettingsSecurityRoute,
  TicketingOrganizersRoute: TicketingOrganizersRouteWithChildren,
  TicketingShowsRoute: TicketingShowsRouteWithChildren,
  TicketingVenuesRoute: TicketingVenuesRouteWithChildren,
  SettingsIndexRoute: SettingsIndexRoute,
  SettingsSalesCustomerGroupsRoute: SettingsSalesCustomerGroupsRoute,
  SettingsSalesCustomerTypesRoute: SettingsSalesCustomerTypesRoute,
  SettingsSalesTestBasicsRoute: SettingsSalesTestBasicsRoute,
  SettingsSalesTestTreesRoute: SettingsSalesTestTreesRoute,
  SettingsTicketingEventTypesRoute: SettingsTicketingEventTypesRoute,
  SettingsTicketingVenueTypesRoute: SettingsTicketingVenueTypesRoute,
  TicketingEventsEventIdInventoryRoute: TicketingEventsEventIdInventoryRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
