/**
 * Application Tab Configuration
 *
 * Defines all routes and their metadata for the tab management system.
 * This replaces hardcoded logic in TabManager and allows for better maintainability.
 */

import type { TabConfiguration } from "@truths/custom-ui";
import { RECENT_EVENTS_BOOKINGS_TITLE } from "@truths/shared";

/**
 * Module order for tab grouping and dropdown display
 * This determines the order in which modules appear in the dropdown menu
 */
export const moduleOrder = [
    "Pinned",
    "General",
    "Sales & Bookings",
    "Ticketing",
    "Users",
    "Settings",
    "Other",
];

export const tabConfiguration: TabConfiguration = {
    tabs: [
        // General/Home
        {
            path: "/activity",
            title: RECENT_EVENTS_BOOKINGS_TITLE,
            iconName: "Activity",
            pageType: "list",
            module: "General",
            group: "primary",
            sequence: 2,
            priority: 2,
        },
        {
            path: "/",
            title: "Home",
            iconName: "Home",
            pageType: "list",
            module: "General",
            group: "primary",
            sequence: 1,
            priority: 1,
        },

        // Users module
        {
            path: "/users",
            title: "Users",
            iconName: "Users",
            pageType: "list",
            module: "Users",
            group: "users",
            sequence: 1,
            priority: 1,
        },
        {
            path: "/users/$id",
            title: "User",
            iconName: "User",
            pageType: "detail",
            module: "users",
            group: "primary",
            sequence: 2,
            priority: 2,
        },
        {
            path: "/profile",
            title: "Profile",
            iconName: "User",
            pageType: "detail",
            module: "profile",
            group: "secondary",
            sequence: 1,
            priority: 3,
        },
        {
            path: "/settings/profile",
            title: "Profile Settings",
            iconName: "User",
            pageType: "detail",
            module: "Settings",
            group: "profile",
            sequence: 2,
            priority: 1,
        },

        // Sales & Bookings module
        {
            path: "/sales/customers",
            title: "Customers",
            iconName: "Users",
            pageType: "list",
            module: "Sales & Bookings",
            group: "customers",
            sequence: 1,
            priority: 1,
        },
        {
            path: "/sales/customers/$id",
            title: "Customer",
            iconName: "User",
            pageType: "detail",
            module: "Sales & Bookings",
            group: "customers",
            sequence: 2,
            priority: 2,
        },
        {
            path: "/sales/bookings",
            title: "Bookings",
            iconName: "Calendar",
            pageType: "list",
            module: "Sales & Bookings",
            group: "bookings",
            sequence: 1,
            priority: 3,
        },
        {
            path: "/sales/bookings/$id",
            title: "Booking",
            iconName: "Calendar",
            pageType: "detail",
            module: "Sales & Bookings",
            group: "bookings",
            sequence: 2,
            priority: 4,
        },
        {
            path: "/bookings",
            title: "Bookings",
            iconName: "Calendar",
            pageType: "list",
            module: "Sales & Bookings",
            group: "bookings",
            sequence: 5,
            priority: 11,
        },
        {
            path: "/sales/employees",
            title: "Employees",
            iconName: "Users",
            pageType: "list",
            module: "Sales & Bookings",
            group: "employees",
            sequence: 1,
            priority: 5,
        },
        {
            path: "/sales/employees/$id",
            title: "Employee",
            iconName: "User",
            pageType: "detail",
            module: "Sales & Bookings",
            group: "employees",
            sequence: 2,
            priority: 6,
        },
        {
            path: "/sales/payments",
            title: "Payments",
            iconName: "CreditCard",
            pageType: "list",
            module: "Sales & Bookings",
            group: "payments",
            sequence: 1,
            priority: 7,
        },
        {
            path: "/sales/payments/$id",
            title: "Payment",
            iconName: "CreditCard",
            pageType: "detail",
            module: "Sales & Bookings",
            group: "payments",
            sequence: 2,
            priority: 8,
        },
        {
            path: "/sales/explore",
            title: "Explore",
            iconName: "Search",
            pageType: "list",
            module: "Sales & Bookings",
            group: "explore",
            sequence: 1,
            priority: 9,
        },
        {
            path: "/explore",
            title: "Explore",
            iconName: "Search",
            pageType: "list",
            module: "Sales & Bookings",
            group: "explore",
            sequence: 2,
            priority: 10,
        },

        // Ticketing/Venues module
        {
            path: "/ticketing/venues",
            title: "Venues",
            iconName: "MapPin",
            pageType: "list",
            module: "Ticketing",
            group: "venues",
            sequence: 1,
            priority: 1,
        },
        {
            path: "/ticketing/venues/$id",
            title: "Venue",
            iconName: "MapPin",
            pageType: "detail",
            module: "Ticketing",
            group: "venues",
            sequence: 2,
            priority: 2,
        },
        {
            path: "/ticketing/venues/$id/seats/designer",
            title: "Seat Designer",
            iconName: "LayoutGrid",
            pageType: "sub-detail",
            module: "Ticketing",
            group: "venues",
            sequence: 3,
            priority: 3,
        },
        {
            path: "/ticketing/events",
            title: "Events",
            iconName: "Calendar",
            pageType: "list",
            module: "Ticketing",
            group: "events",
            sequence: 4,
            priority: 4,
        },
        {
            path: "/ticketing/events/$id",
            title: "Event",
            iconName: "Calendar",
            pageType: "detail",
            module: "Ticketing",
            group: "events",
            sequence: 5,
            priority: 5,
        },
        {
            path: "/ticketing/events/$eventId/inventory",
            title: "Event Inventory",
            iconName: "Package",
            pageType: "sub-detail",
            module: "Ticketing",
            group: "events",
            sequence: 6,
            priority: 6,
            loadingOnAdded: true,
        },
        {
            path: "/ticketing/shows",
            title: "Shows",
            iconName: "Play",
            pageType: "list",
            module: "Ticketing",
            group: "shows",
            sequence: 1,
            priority: 8,
        },
        {
            path: "/ticketing/shows/$id",
            title: "Show",
            iconName: "Play",
            pageType: "detail",
            module: "Ticketing",
            group: "shows",
            sequence: 2,
            priority: 9,
        },
        {
            path: "/ticketing/organizers",
            title: "Organizers",
            iconName: "Users",
            pageType: "list",
            module: "Ticketing",
            group: "organizers",
            sequence: 1,
            priority: 6,
        },
        {
            path: "/ticketing/organizers/$id",
            title: "Organizer",
            iconName: "User",
            pageType: "detail",
            module: "Ticketing",
            group: "organizers",
            sequence: 2,
            priority: 7,
        },

        // Settings module
        {
            path: "/settings",
            title: "Settings",
            iconName: "Settings",
            pageType: "list",
            module: "Settings",
            group: "settings",
            sequence: 1,
            priority: 1,
        },
        {
            path: "/settings/account",
            title: "Account Settings",
            iconName: "User",
            pageType: "detail",
            module: "Settings",
            group: "settings",
            sequence: 2,
            priority: 2,
        },
        {
            path: "/settings/appearance",
            title: "Appearance",
            iconName: "Palette",
            pageType: "detail",
            module: "Settings",
            group: "settings",
            sequence: 3,
            priority: 4,
        },
        {
            path: "/settings/notifications",
            title: "Notifications",
            iconName: "Bell",
            pageType: "detail",
            module: "Settings",
            group: "settings",
            sequence: 1,
            priority: 3,
        },
        {
            path: "/settings/language",
            title: "Language",
            iconName: "Globe",
            pageType: "detail",
            module: "Settings",
            group: "settings",
            sequence: 2,
            priority: 5,
        },
        {
            path: "/settings/security",
            title: "Security",
            iconName: "Shield",
            pageType: "detail",
            module: "Settings",
            group: "settings",
            sequence: 3,
            priority: 6,
        },
    ],
};