"""Add

Revision ID: 0890508d4029
Revises: 1453227fa30b
Create Date: 2026-01-03 23:02:19.858775

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0890508d4029'
down_revision = '1453227fa30b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('venue_types',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tenant_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_venue_types_code'), 'venue_types', ['code'], unique=False)
    op.create_index(op.f('ix_venue_types_is_active'), 'venue_types', ['is_active'], unique=False)
    op.create_index(op.f('ix_venue_types_is_deleted'), 'venue_types', ['is_deleted'], unique=False)
    op.create_index('ix_venue_types_tenant_active', 'venue_types', ['tenant_id', 'is_active'], unique=False)
    op.create_index('ix_venue_types_tenant_code', 'venue_types', ['tenant_id', 'code'], unique=True)
    op.create_index('ix_venue_types_tenant_deleted', 'venue_types', ['tenant_id', 'is_deleted'], unique=False)
    op.create_index(op.f('ix_venue_types_tenant_id'), 'venue_types', ['tenant_id'], unique=False)
    op.drop_index('ix_audit_logs_event_type', table_name='audit_logs')
    op.create_index('ix_audit_logs_event_type', 'audit_logs', ['event_type', 'timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_audit_logs_event_type', table_name='audit_logs')
    op.create_index('ix_audit_logs_event_type', 'audit_logs', ['event_type'], unique=False)
    op.drop_index(op.f('ix_venue_types_tenant_id'), table_name='venue_types')
    op.drop_index('ix_venue_types_tenant_deleted', table_name='venue_types')
    op.drop_index('ix_venue_types_tenant_code', table_name='venue_types')
    op.drop_index('ix_venue_types_tenant_active', table_name='venue_types')
    op.drop_index(op.f('ix_venue_types_is_deleted'), table_name='venue_types')
    op.drop_index(op.f('ix_venue_types_is_active'), table_name='venue_types')
    op.drop_index(op.f('ix_venue_types_code'), table_name='venue_types')
    op.drop_table('venue_types')
    # ### end Alembic commands ###

