"""add_venue_contact_address_description_fields

Revision ID: 1453227fa30b
Revises: bedc3fbbdbd0
Create Date: 2026-01-03 18:49:34.786312

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1453227fa30b'
down_revision = 'bedc3fbbdbd0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_audit_logs_event_type', table_name='audit_logs')
    op.create_index(op.f('ix_audit_logs_event_type'), 'audit_logs', ['event_type'], unique=False)
    op.alter_column('customers', 'total_purchase_amount',
               existing_type=sa.NUMERIC(),
               type_=sa.Float(),
               existing_nullable=False,
               existing_server_default=sa.text('0.0'))
    op.alter_column('customers', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('customers', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.create_index(op.f('ix_customers_is_active'), 'customers', ['is_active'], unique=False)
    op.drop_index('ix_tags_tenant_name', table_name='tags')
    op.create_foreign_key(None, 'tickets', 'bookings', ['booking_id'], ['id'])
    op.add_column('venues', sa.Column('description', sa.String(), nullable=True))
    op.add_column('venues', sa.Column('phone', sa.String(), nullable=True))
    op.add_column('venues', sa.Column('email', sa.String(), nullable=True))
    op.add_column('venues', sa.Column('website', sa.String(), nullable=True))
    op.add_column('venues', sa.Column('street_address', sa.String(), nullable=True))
    op.add_column('venues', sa.Column('city', sa.String(), nullable=True))
    op.add_column('venues', sa.Column('state_province', sa.String(), nullable=True))
    op.add_column('venues', sa.Column('postal_code', sa.String(), nullable=True))
    op.add_column('venues', sa.Column('country', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('venues', 'country')
    op.drop_column('venues', 'postal_code')
    op.drop_column('venues', 'state_province')
    op.drop_column('venues', 'city')
    op.drop_column('venues', 'street_address')
    op.drop_column('venues', 'website')
    op.drop_column('venues', 'email')
    op.drop_column('venues', 'phone')
    op.drop_column('venues', 'description')
    op.drop_constraint(None, 'tickets', type_='foreignkey')
    op.create_index('ix_tags_tenant_name', 'tags', ['tenant_id', 'name'], unique=False)
    op.drop_index(op.f('ix_customers_is_active'), table_name='customers')
    op.alter_column('customers', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.alter_column('customers', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.alter_column('customers', 'total_purchase_amount',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(),
               existing_nullable=False,
               existing_server_default=sa.text('0.0'))
    op.drop_index(op.f('ix_audit_logs_event_type'), table_name='audit_logs')
    op.create_index('ix_audit_logs_event_type', 'audit_logs', ['event_type', 'timestamp'], unique=False)
    # ### end Alembic commands ###

