"""remove_customer_priority

Revision ID: 1774e7cf0d30
Revises: 9b71b9be1fd6
Create Date: 2026-01-07 12:11:10.899616

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1774e7cf0d30'
down_revision = '9b71b9be1fd6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_customers_priority', table_name='customers')
    op.drop_column('customers', 'priority')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('priority', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_index('ix_customers_priority', 'customers', ['priority'], unique=False)
    # ### end Alembic commands ###

