"""Add

Revision ID: 32209b7224de
Revises: 0a9027a34aba
Create Date: 2026-01-06 15:22:01.933313

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32209b7224de'
down_revision = '0a9027a34aba'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employees',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tenant_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_employees_code'), 'employees', ['code'], unique=False)
    op.create_index(op.f('ix_employees_is_active'), 'employees', ['is_active'], unique=False)
    op.create_index(op.f('ix_employees_is_deleted'), 'employees', ['is_deleted'], unique=False)
    op.create_index('ix_employees_tenant_active', 'employees', ['tenant_id', 'is_active'], unique=False)
    op.create_index('ix_employees_tenant_code', 'employees', ['tenant_id', 'code'], unique=True)
    op.create_index('ix_employees_tenant_deleted', 'employees', ['tenant_id', 'is_deleted'], unique=False)
    op.create_index(op.f('ix_employees_tenant_id'), 'employees', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_employees_tenant_id'), table_name='employees')
    op.drop_index('ix_employees_tenant_deleted', table_name='employees')
    op.drop_index('ix_employees_tenant_code', table_name='employees')
    op.drop_index('ix_employees_tenant_active', table_name='employees')
    op.drop_index(op.f('ix_employees_is_deleted'), table_name='employees')
    op.drop_index(op.f('ix_employees_is_active'), table_name='employees')
    op.drop_index(op.f('ix_employees_code'), table_name='employees')
    op.drop_table('employees')
    # ### end Alembic commands ###

