"""Add

Revision ID: 63a95d184528
Revises: 9f3c74a776e8
Create Date: 2025-12-22 00:18:18.113427

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '63a95d184528'
down_revision = '9f3c74a776e8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bookings',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tenant_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bookings_code'), 'bookings', ['code'], unique=False)
    op.create_index(op.f('ix_bookings_is_active'), 'bookings', ['is_active'], unique=False)
    op.create_index(op.f('ix_bookings_is_deleted'), 'bookings', ['is_deleted'], unique=False)
    op.create_index('ix_bookings_tenant_active', 'bookings', ['tenant_id', 'is_active'], unique=False)
    op.create_index('ix_bookings_tenant_code', 'bookings', ['tenant_id', 'code'], unique=True)
    op.create_index('ix_bookings_tenant_deleted', 'bookings', ['tenant_id', 'is_deleted'], unique=False)
    op.create_index(op.f('ix_bookings_tenant_id'), 'bookings', ['tenant_id'], unique=False)
    op.alter_column('file_uploads', 'uploaded_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('file_uploads', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('file_uploads', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index('ix_file_uploads_tenant_id', table_name='file_uploads')
    op.create_index(op.f('ix_file_uploads_tenant_id'), 'file_uploads', ['tenant_id'], unique=False)
    op.drop_index('ix_file_uploads_uploaded_by', table_name='file_uploads')
    op.create_index(op.f('ix_file_uploads_uploaded_by'), 'file_uploads', ['uploaded_by'], unique=False)
    op.create_index(op.f('ix_file_uploads_uploaded_at'), 'file_uploads', ['uploaded_at'], unique=False)
    op.alter_column('layouts', 'design_mode',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=False,
               existing_server_default=sa.text("'seat-level'::text"))
    op.drop_constraint('fk_layouts_file_id', 'layouts', type_='foreignkey')
    op.create_foreign_key(None, 'layouts', 'file_uploads', ['file_id'], ['id'])
    op.alter_column('seats', 'layout_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('seats', 'section_id',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=False)
    op.create_index('ix_seats_section', 'seats', ['tenant_id', 'section_id'], unique=False)
    op.create_index(op.f('ix_seats_section_id'), 'seats', ['section_id'], unique=False)
    op.drop_constraint('fk_seats_section_id', 'seats', type_='foreignkey')
    op.create_foreign_key(None, 'seats', 'sections', ['section_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'seats', type_='foreignkey')
    op.create_foreign_key('fk_seats_section_id', 'seats', 'sections', ['section_id'], ['id'], ondelete='RESTRICT')
    op.drop_index(op.f('ix_seats_section_id'), table_name='seats')
    op.drop_index('ix_seats_section', table_name='seats')
    op.alter_column('seats', 'section_id',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('seats', 'layout_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_constraint(None, 'layouts', type_='foreignkey')
    op.create_foreign_key('fk_layouts_file_id', 'layouts', 'file_uploads', ['file_id'], ['id'], ondelete='SET NULL')
    op.alter_column('layouts', 'design_mode',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=False,
               existing_server_default=sa.text("'seat-level'::text"))
    op.drop_index(op.f('ix_file_uploads_uploaded_at'), table_name='file_uploads')
    op.drop_index(op.f('ix_file_uploads_uploaded_by'), table_name='file_uploads')
    op.create_index('ix_file_uploads_uploaded_by', 'file_uploads', ['tenant_id', 'uploaded_by'], unique=False)
    op.drop_index(op.f('ix_file_uploads_tenant_id'), table_name='file_uploads')
    op.create_index('ix_file_uploads_tenant_id', 'file_uploads', ['tenant_id', sa.text('uploaded_at DESC')], unique=False)
    op.alter_column('file_uploads', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('file_uploads', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('file_uploads', 'uploaded_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_bookings_tenant_id'), table_name='bookings')
    op.drop_index('ix_bookings_tenant_deleted', table_name='bookings')
    op.drop_index('ix_bookings_tenant_code', table_name='bookings')
    op.drop_index('ix_bookings_tenant_active', table_name='bookings')
    op.drop_index(op.f('ix_bookings_is_deleted'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_is_active'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_code'), table_name='bookings')
    op.drop_table('bookings')
    # ### end Alembic commands ###

