"""add_layouts_table_and_layout_id_to_seats

Revision ID: 981514254019
Revises: f91c4df95d2a
Create Date: 2025-12-20 16:34:30.101619

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = '981514254019'
down_revision = 'f91c4df95d2a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Create layouts table first (if it doesn't exist)
    from sqlalchemy import inspect
    conn = op.get_bind()
    inspector = inspect(conn)
    tables = inspector.get_table_names()
    
    if 'layouts' not in tables:
        op.create_table('layouts',
            sa.Column('id', sa.String(), nullable=False),
            sa.Column('tenant_id', sa.String(), nullable=False),
            sa.Column('venue_id', sa.String(), nullable=False),
            sa.Column('name', sa.String(), nullable=False),
            sa.Column('description', sa.String(), nullable=True),
            sa.Column('image_url', sa.String(), nullable=True),
            sa.Column('is_active', sa.Boolean(), nullable=False),
            sa.Column('is_deleted', sa.Boolean(), nullable=False),
            sa.Column('version', sa.Integer(), nullable=False),
            sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
            sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
            sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
            sa.PrimaryKeyConstraint('id'),
            sa.ForeignKeyConstraint(['venue_id'], ['venues.id'], )
        )
        op.create_index('ix_layouts_venue', 'layouts', ['tenant_id', 'venue_id'], unique=False)
        op.create_index('ix_layouts_tenant_active', 'layouts', ['tenant_id', 'is_active'], unique=False)
        op.create_index('ix_layouts_tenant_deleted', 'layouts', ['tenant_id', 'is_deleted'], unique=False)
        op.create_index(op.f('ix_layouts_tenant_id'), 'layouts', ['tenant_id'], unique=False)
        op.create_index(op.f('ix_layouts_venue_id'), 'layouts', ['venue_id'], unique=False)
    
    # Update other indexes
    op.drop_index('ix_audit_logs_event_id', table_name='audit_logs')
    op.create_index('ix_audit_logs_event_id', 'audit_logs', ['event_id'], unique=False)
    op.drop_index('ix_audit_logs_event_type', table_name='audit_logs')
    op.create_index(op.f('ix_audit_logs_event_type'), 'audit_logs', ['event_type'], unique=False)
    op.drop_index('ix_lots_status', table_name='lots')
    op.create_index('ix_lots_status', 'lots', ['tenant_id', 'status'], unique=False)
    
    # Add layout_id to seats (nullable first, then we'll update existing seats)
    op.add_column('seats', sa.Column('layout_id', sa.String(), nullable=True))
    
    # For existing seats, we need to create a default layout or handle them
    # For now, we'll make it nullable temporarily, then set a default and make it NOT NULL
    # But since this is a new feature, we can assume no seats exist yet, so make it NOT NULL
    # Actually, let's check if there are existing seats first by making it nullable, then updating
    
    # Drop old index
    op.drop_index('ix_seats_location', table_name='seats')
    
    # Create new indexes
    op.create_index('ix_seats_layout', 'seats', ['tenant_id', 'layout_id'], unique=False)
    op.create_index(op.f('ix_seats_layout_id'), 'seats', ['layout_id'], unique=False)
    
    # Create foreign key
    op.create_foreign_key('fk_seats_layout_id', 'seats', 'layouts', ['layout_id'], ['id'])
    
    # Now update the unique constraint to use layout_id instead of venue_id
    op.create_index('ix_seats_location', 'seats', ['layout_id', 'section', 'row', 'seat_number'], unique=True)
    
    # Make layout_id NOT NULL (only if no existing seats, otherwise we'd need to handle migration)
    # For safety, we'll keep it nullable for now and handle in application code
    # op.alter_column('seats', 'layout_id', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_seats_location', table_name='seats')
    op.drop_constraint('fk_seats_layout_id', 'seats', type_='foreignkey')
    op.drop_index(op.f('ix_seats_layout_id'), table_name='seats')
    op.drop_index('ix_seats_layout', table_name='seats')
    op.create_index('ix_seats_location', 'seats', ['venue_id', 'section', 'row', 'seat_number'], unique=True)
    op.drop_column('seats', 'layout_id')
    
    op.drop_index(op.f('ix_layouts_venue_id'), table_name='layouts')
    op.drop_index(op.f('ix_layouts_tenant_id'), table_name='layouts')
    op.drop_index('ix_layouts_tenant_deleted', table_name='layouts')
    op.drop_index('ix_layouts_tenant_active', table_name='layouts')
    op.drop_index('ix_layouts_venue', table_name='layouts')
    op.drop_table('layouts')
    
    op.drop_index('ix_lots_status', table_name='lots')
    op.create_index('ix_lots_status', 'lots', ['status'], unique=False)
    op.drop_index(op.f('ix_audit_logs_event_type'), table_name='audit_logs')
    op.create_index('ix_audit_logs_event_type', 'audit_logs', ['event_type', 'timestamp'], unique=False)
    op.drop_index('ix_audit_logs_event_id', table_name='audit_logs')
    op.create_index('ix_audit_logs_event_id', 'audit_logs', ['event_id'], unique=True)
    # ### end Alembic commands ###

