"""add salesperson_id to bookings

Revision ID: 9b71b9be1fd6
Revises: 32209b7224de
Create Date: 2026-01-06 16:47:21.987106

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9b71b9be1fd6'
down_revision = '32209b7224de'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_audit_logs_event_id', table_name='audit_logs')
    op.create_index('ix_audit_logs_event_id', 'audit_logs', ['event_id'], unique=False)
    op.add_column('bookings', sa.Column('salesperson_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.create_index(op.f('ix_bookings_salesperson_id'), 'bookings', ['salesperson_id'], unique=False)
    op.create_foreign_key(None, 'bookings', 'employees', ['salesperson_id'], ['id'])
    op.alter_column('employees', 'timezone',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_server_default=sa.text("'UTC'::character varying"))
    op.alter_column('employees', 'skills',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('employees', 'assigned_territories',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('employees', 'quota_config',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.create_index(op.f('ix_employees_department'), 'employees', ['department'], unique=False)
    op.create_index(op.f('ix_employees_manager_id'), 'employees', ['manager_id'], unique=False)
    op.drop_constraint('fk_employees_manager', 'employees', type_='foreignkey')
    op.create_foreign_key(None, 'employees', 'employees', ['manager_id'], ['id'])
    op.drop_index('ix_file_uploads_uploaded_by', table_name='file_uploads')
    op.create_index(op.f('ix_file_uploads_uploaded_by'), 'file_uploads', ['uploaded_by'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_file_uploads_uploaded_by'), table_name='file_uploads')
    op.create_index('ix_file_uploads_uploaded_by', 'file_uploads', ['tenant_id', 'uploaded_by'], unique=False)
    op.drop_constraint(None, 'employees', type_='foreignkey')
    op.create_foreign_key('fk_employees_manager', 'employees', 'employees', ['manager_id'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_employees_manager_id'), table_name='employees')
    op.drop_index(op.f('ix_employees_department'), table_name='employees')
    op.alter_column('employees', 'quota_config',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('employees', 'assigned_territories',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('employees', 'skills',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('employees', 'timezone',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text("'UTC'::character varying"))
    op.drop_constraint(None, 'bookings', type_='foreignkey')
    op.drop_index(op.f('ix_bookings_salesperson_id'), table_name='bookings')
    op.drop_column('bookings', 'salesperson_id')
    op.drop_index('ix_audit_logs_event_id', table_name='audit_logs')
    op.create_index('ix_audit_logs_event_id', 'audit_logs', ['event_id'], unique=True)
    # ### end Alembic commands ###

