"""add_payments_table

Revision ID: ad260265bbe7
Revises: 073046ccb44b
Create Date: 2026-01-01 13:07:02.111713

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad260265bbe7'
down_revision = '073046ccb44b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_audit_logs_event_type', table_name='audit_logs')
    op.create_index(op.f('ix_audit_logs_event_type'), 'audit_logs', ['event_type'], unique=False)
    op.drop_index('ix_file_uploads_tenant_id', table_name='file_uploads')
    op.create_index('ix_file_uploads_tenant_id', 'file_uploads', ['tenant_id', 'uploaded_at'], unique=False)
    op.drop_index('ix_file_uploads_uploaded_by', table_name='file_uploads')
    op.create_index(op.f('ix_file_uploads_uploaded_by'), 'file_uploads', ['uploaded_by'], unique=False)
    op.create_foreign_key(None, 'tickets', 'bookings', ['booking_id'], ['id'])
    
    # Create payments table
    op.create_table(
        'payments',
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('tenant_id', sa.String(), nullable=False),
        sa.Column('booking_id', sa.String(), nullable=False),
        sa.Column('amount', sa.Float(), nullable=False),
        sa.Column('currency', sa.String(), nullable=False),
        sa.Column('payment_method', sa.Enum('credit_card', 'debit_card', 'paypal', 'bank_transfer', 'cash', 'other', name='paymentmethodenum', native_enum=False), nullable=False),
        sa.Column('status', sa.Enum('pending', 'processing', 'completed', 'failed', 'refunded', 'cancelled', name='paymentstatusenum', native_enum=False), nullable=False),
        sa.Column('transaction_reference', sa.String(), nullable=True),
        sa.Column('notes', sa.String(), nullable=True),
        sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('version', sa.Integer(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_payments_tenant_booking', 'payments', ['tenant_id', 'booking_id'], unique=False)
    op.create_index('ix_payments_tenant_status', 'payments', ['tenant_id', 'status'], unique=False)
    op.create_index('ix_payments_booking', 'payments', ['booking_id'], unique=False)
    op.create_index('ix_payments_transaction_ref', 'payments', ['transaction_reference'], unique=False)
    op.create_index(op.f('ix_payments_payment_method'), 'payments', ['payment_method'], unique=False)
    op.create_index(op.f('ix_payments_status'), 'payments', ['status'], unique=False)
    op.create_index(op.f('ix_payments_tenant_id'), 'payments', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payments_tenant_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_status'), table_name='payments')
    op.drop_index(op.f('ix_payments_payment_method'), table_name='payments')
    op.drop_index('ix_payments_transaction_ref', table_name='payments')
    op.drop_index('ix_payments_booking', table_name='payments')
    op.drop_index('ix_payments_tenant_status', table_name='payments')
    op.drop_index('ix_payments_tenant_booking', table_name='payments')
    op.drop_table('payments')
    op.drop_constraint(None, 'tickets', type_='foreignkey')
    op.drop_index(op.f('ix_file_uploads_uploaded_by'), table_name='file_uploads')
    op.create_index('ix_file_uploads_uploaded_by', 'file_uploads', ['tenant_id', 'uploaded_by'], unique=False)
    op.drop_index('ix_file_uploads_tenant_id', table_name='file_uploads')
    op.create_index('ix_file_uploads_tenant_id', 'file_uploads', ['tenant_id'], unique=False)
    op.drop_index(op.f('ix_audit_logs_event_type'), table_name='audit_logs')
    op.create_index('ix_audit_logs_event_type', 'audit_logs', ['event_type', 'timestamp'], unique=False)
    # ### end Alembic commands ###

