"""Add marker_fill_transparency to layouts

Revision ID: c9d8e7f6g5h4
Revises: a1b2c3d4e5f6
Create Date: 2026-02-11 15:30:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c9d8e7f6g5h4'
down_revision = 'a1b2c3d4e5f6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('layouts', sa.Column('marker_fill_transparency', sa.Float(), nullable=False, server_default='1.0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('layouts', 'marker_fill_transparency')
    # ### end Alembic commands ###
