"""Add marker_fill_transparency to sections

Revision ID: d0e1f2a3b4c5
Revises: c9d8e7f6g5h4
Create Date: 2026-02-11 18:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd0e1f2a3b4c5'
down_revision = 'c9d8e7f6g5h4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sections', sa.Column('marker_fill_transparency', sa.Float(), nullable=False, server_default='1.0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sections', 'marker_fill_transparency')
    # ### end Alembic commands ###
