"""add_booking_and_items

Revision ID: d38b344f701d
Revises: e24e85d8b184
Create Date: 2026-01-01 10:27:41.926101

Consolidates booking into a single model with line items support.
"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = 'd38b344f701d'
down_revision = 'e24e85d8b184'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop old bookings table if it exists (master data model - no longer needed)
    # Check if table exists before dropping
    from sqlalchemy import inspect
    bind = op.get_bind()
    inspector = inspect(bind)
    if 'bookings' in inspector.get_table_names():
        # Drop foreign key constraints first
        # Check if tickets table exists and has the constraint
        if 'tickets' in inspector.get_table_names():
            try:
                # Get all foreign keys from tickets table
                fks = inspector.get_foreign_keys('tickets')
                for fk in fks:
                    if fk['referred_table'] == 'bookings':
                        op.drop_constraint(fk['name'], 'tickets', type_='foreignkey')
            except Exception as e:
                pass
        
        # Check if booking_items table exists and has the constraint
        if 'booking_items' in inspector.get_table_names():
            try:
                # Get all foreign keys from booking_items table
                fks = inspector.get_foreign_keys('booking_items')
                for fk in fks:
                    if fk['referred_table'] == 'bookings':
                        op.drop_constraint(fk['name'], 'booking_items', type_='foreignkey')
            except Exception as e:
                pass
        
        # Drop old indexes
        try:
            op.drop_index('ix_bookings_tenant_code', table_name='bookings')
        except:
            pass
        try:
            op.drop_index('ix_bookings_tenant_active', table_name='bookings')
        except:
            pass
        try:
            op.drop_index('ix_bookings_tenant_deleted', table_name='bookings')
        except:
            pass
        
        # Now drop the table
        op.drop_table('bookings')
    
    # Create new bookings table for booking transactions
    op.create_table('bookings',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tenant_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('booking_number', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('customer_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('event_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RESERVED', 'CONFIRMED', 'PAID', 'CANCELLED', 'REFUNDED', name='bookingstatusenum', native_enum=False), nullable=True),
    sa.Column('subtotal_amount', sa.Float(), nullable=False),
    sa.Column('discount_amount', sa.Float(), nullable=False),
    sa.Column('discount_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('discount_value', sa.Float(), nullable=True),
    sa.Column('tax_amount', sa.Float(), nullable=False),
    sa.Column('tax_rate', sa.Float(), nullable=False),
    sa.Column('total_amount', sa.Float(), nullable=False),
    sa.Column('currency', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('payment_status', sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', 'REFUNDED', name='paymentstatusenum', native_enum=False), nullable=True),
    sa.Column('payment_method', sa.Enum('CREDIT_CARD', 'DEBIT_CARD', 'PAYPAL', 'BANK_TRANSFER', 'CASH', 'OTHER', name='paymentmethodenum', native_enum=False), nullable=True),
    sa.Column('payment_transaction_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('reserved_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancellation_reason', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bookings_booking_number'), 'bookings', ['booking_number'], unique=True)
    op.create_index(op.f('ix_bookings_customer_id'), 'bookings', ['customer_id'], unique=False)
    op.create_index(op.f('ix_bookings_event_id'), 'bookings', ['event_id'], unique=False)
    op.create_index(op.f('ix_bookings_payment_status'), 'bookings', ['payment_status'], unique=False)
    op.create_index(op.f('ix_bookings_payment_transaction_id'), 'bookings', ['payment_transaction_id'], unique=False)
    op.create_index(op.f('ix_bookings_status'), 'bookings', ['status'], unique=False)
    op.create_index('ix_bookings_tenant_customer', 'bookings', ['tenant_id', 'customer_id'], unique=False)
    op.create_index('ix_bookings_tenant_event', 'bookings', ['tenant_id', 'event_id'], unique=False)
    op.create_index(op.f('ix_bookings_tenant_id'), 'bookings', ['tenant_id'], unique=False)
    op.create_index('ix_bookings_tenant_status', 'bookings', ['tenant_id', 'status'], unique=False)
    
    # Create booking_items table (will skip if already exists)
    # Refresh inspector to get current state
    inspector = inspect(bind)
    if 'booking_items' not in inspector.get_table_names():
        op.create_table('booking_items',
        sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('tenant_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('booking_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('event_seat_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('ticket_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('section_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('row_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('seat_number', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('unit_price', sa.Float(), nullable=False),
        sa.Column('total_price', sa.Float(), nullable=False),
        sa.Column('currency', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('ticket_number', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('ticket_status', sa.Enum('AVAILABLE', 'RESERVED', 'CONFIRMED', 'CANCELLED', 'TRANSFERRED', 'USED', name='ticketstatusenum', native_enum=False), nullable=True),
        sa.Column('version', sa.Integer(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ),
        sa.ForeignKeyConstraint(['event_seat_id'], ['event_seats.id'], ),
        sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index('ix_booking_items_booking', 'booking_items', ['tenant_id', 'booking_id'], unique=False)
        op.create_index(op.f('ix_booking_items_booking_id'), 'booking_items', ['booking_id'], unique=False)
        op.create_index('ix_booking_items_event_seat', 'booking_items', ['event_seat_id'], unique=False)
        op.create_index(op.f('ix_booking_items_event_seat_id'), 'booking_items', ['event_seat_id'], unique=False)
        op.create_index(op.f('ix_booking_items_tenant_id'), 'booking_items', ['tenant_id'], unique=False)
        op.create_index('ix_booking_items_ticket', 'booking_items', ['ticket_id'], unique=False)
        op.create_index(op.f('ix_booking_items_ticket_id'), 'booking_items', ['ticket_id'], unique=False)
        op.create_index(op.f('ix_booking_items_ticket_number'), 'booking_items', ['ticket_number'], unique=False)
    
    op.drop_index('ix_file_uploads_tenant_id', table_name='file_uploads')
    op.create_index(op.f('ix_file_uploads_tenant_id'), 'file_uploads', ['tenant_id'], unique=False)
    op.drop_index('ix_file_uploads_uploaded_by', table_name='file_uploads')
    op.create_index('ix_file_uploads_uploaded_by', 'file_uploads', ['tenant_id', 'uploaded_by'], unique=False)
    op.alter_column('tickets', 'price',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Float(),
               comment=None,
               existing_comment='Ticket price',
               existing_nullable=False,
               existing_server_default=sa.text('0.0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tickets', 'price',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=10, scale=2),
               comment='Ticket price',
               existing_nullable=False,
               existing_server_default=sa.text('0.0'))
    op.drop_index('ix_file_uploads_uploaded_by', table_name='file_uploads')
    op.create_index('ix_file_uploads_uploaded_by', 'file_uploads', ['uploaded_by'], unique=False)
    op.drop_index(op.f('ix_file_uploads_tenant_id'), table_name='file_uploads')
    op.create_index('ix_file_uploads_tenant_id', 'file_uploads', ['tenant_id', 'uploaded_at'], unique=False)
    op.drop_index(op.f('ix_booking_items_ticket_number'), table_name='booking_items')
    op.drop_index(op.f('ix_booking_items_ticket_id'), table_name='booking_items')
    op.drop_index('ix_booking_items_ticket', table_name='booking_items')
    op.drop_index(op.f('ix_booking_items_tenant_id'), table_name='booking_items')
    op.drop_index(op.f('ix_booking_items_event_seat_id'), table_name='booking_items')
    op.drop_index('ix_booking_items_event_seat', table_name='booking_items')
    op.drop_index(op.f('ix_booking_items_booking_id'), table_name='booking_items')
    op.drop_index('ix_booking_items_booking', table_name='booking_items')
    op.drop_table('booking_items')
    op.drop_index('ix_bookings_tenant_status', table_name='bookings')
    op.drop_index(op.f('ix_bookings_tenant_id'), table_name='bookings')
    op.drop_index('ix_bookings_tenant_event', table_name='bookings')
    op.drop_index('ix_bookings_tenant_customer', table_name='bookings')
    op.drop_index(op.f('ix_bookings_status'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_payment_transaction_id'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_payment_status'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_event_id'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_customer_id'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_booking_number'), table_name='bookings')
    op.drop_table('bookings')
    # ### end Alembic commands ###

