"""add_soft_delete_to_event_seat

Revision ID: e7dc2695e428
Revises: 1774e7cf0d30
Create Date: 2026-01-10 15:27:46.445709

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e7dc2695e428'
down_revision = '1774e7cf0d30'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_test_trees_code', table_name='test_trees')
    op.drop_index('ix_test_trees_is_active', table_name='test_trees')
    op.drop_index('ix_test_trees_is_deleted', table_name='test_trees')
    op.drop_index('ix_test_trees_level', table_name='test_trees')
    op.drop_index('ix_test_trees_parent', table_name='test_trees')
    op.drop_index('ix_test_trees_parent_test_tree_id', table_name='test_trees')
    op.drop_index('ix_test_trees_tenant_active', table_name='test_trees')
    op.drop_index('ix_test_trees_tenant_code', table_name='test_trees')
    op.drop_index('ix_test_trees_tenant_deleted', table_name='test_trees')
    op.drop_index('ix_test_trees_tenant_id', table_name='test_trees')
    op.drop_table('test_trees')
    op.drop_index('ix_test_basics_code', table_name='test_basics')
    op.drop_index('ix_test_basics_is_active', table_name='test_basics')
    op.drop_index('ix_test_basics_is_deleted', table_name='test_basics')
    op.drop_index('ix_test_basics_tenant_active', table_name='test_basics')
    op.drop_index('ix_test_basics_tenant_code', table_name='test_basics')
    op.drop_index('ix_test_basics_tenant_deleted', table_name='test_basics')
    op.drop_index('ix_test_basics_tenant_id', table_name='test_basics')
    op.drop_table('test_basics')
    op.drop_index('ix_test_entities_code', table_name='test_entities')
    op.drop_index('ix_test_entities_is_active', table_name='test_entities')
    op.drop_index('ix_test_entities_tenant_active', table_name='test_entities')
    op.drop_index('ix_test_entities_tenant_code', table_name='test_entities')
    op.drop_index('ix_test_entities_tenant_id', table_name='test_entities')
    op.drop_table('test_entities')
    op.drop_index('ix_test_tree_backends_code', table_name='test_tree_backends')
    op.drop_index('ix_test_tree_backends_is_active', table_name='test_tree_backends')
    op.drop_index('ix_test_tree_backends_is_deleted', table_name='test_tree_backends')
    op.drop_index('ix_test_tree_backends_tenant_active', table_name='test_tree_backends')
    op.drop_index('ix_test_tree_backends_tenant_code', table_name='test_tree_backends')
    op.drop_index('ix_test_tree_backends_tenant_deleted', table_name='test_tree_backends')
    op.drop_index('ix_test_tree_backends_tenant_id', table_name='test_tree_backends')
    op.drop_table('test_tree_backends')
    op.drop_index('ix_tests_code', table_name='tests')
    op.drop_index('ix_tests_is_active', table_name='tests')
    op.drop_index('ix_tests_is_deleted', table_name='tests')
    op.drop_index('ix_tests_tenant_active', table_name='tests')
    op.drop_index('ix_tests_tenant_code', table_name='tests')
    op.drop_index('ix_tests_tenant_deleted', table_name='tests')
    op.drop_index('ix_tests_tenant_id', table_name='tests')
    op.drop_table('tests')
    op.drop_index('ix_audit_logs_event_id', table_name='audit_logs')
    op.create_index(op.f('ix_audit_logs_event_id'), 'audit_logs', ['event_id'], unique=True)
    op.drop_index('ix_booking_items_ticket', table_name='booking_items')
    op.add_column('event_seats', sa.Column('is_deleted', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('event_seats', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_event_seats_is_deleted'), 'event_seats', ['is_deleted'], unique=False)
    op.create_index('ix_event_seats_tenant_deleted', 'event_seats', ['tenant_id', 'is_deleted'], unique=False)
    op.drop_index('ix_file_uploads_tenant_id', table_name='file_uploads')
    op.create_index('ix_file_uploads_tenant_id', 'file_uploads', ['tenant_id', 'uploaded_at'], unique=False)
    op.drop_index('ix_file_uploads_uploaded_by', table_name='file_uploads')
    op.create_index('ix_file_uploads_uploaded_by', 'file_uploads', ['tenant_id', 'uploaded_by'], unique=False)
    op.drop_index('ix_payments_booking', table_name='payments')
    op.drop_index('ix_payments_transaction_ref', table_name='payments')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_payments_transaction_ref', 'payments', ['transaction_reference'], unique=False)
    op.create_index('ix_payments_booking', 'payments', ['booking_id'], unique=False)
    op.drop_index('ix_file_uploads_uploaded_by', table_name='file_uploads')
    op.create_index('ix_file_uploads_uploaded_by', 'file_uploads', ['uploaded_by'], unique=False)
    op.drop_index('ix_file_uploads_tenant_id', table_name='file_uploads')
    op.create_index('ix_file_uploads_tenant_id', 'file_uploads', ['tenant_id'], unique=False)
    op.drop_index('ix_event_seats_tenant_deleted', table_name='event_seats')
    op.drop_index(op.f('ix_event_seats_is_deleted'), table_name='event_seats')
    op.drop_column('event_seats', 'deleted_at')
    op.drop_column('event_seats', 'is_deleted')
    op.create_index('ix_booking_items_ticket', 'booking_items', ['ticket_id'], unique=False)
    op.drop_index(op.f('ix_audit_logs_event_id'), table_name='audit_logs')
    op.create_index('ix_audit_logs_event_id', 'audit_logs', ['event_id'], unique=False)
    op.create_table('tests',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('tenant_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('code', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('deactivated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('version', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='tests_pkey')
    )
    op.create_index('ix_tests_tenant_id', 'tests', ['tenant_id'], unique=False)
    op.create_index('ix_tests_tenant_deleted', 'tests', ['tenant_id', 'is_deleted'], unique=False)
    op.create_index('ix_tests_tenant_code', 'tests', ['tenant_id', 'code'], unique=True)
    op.create_index('ix_tests_tenant_active', 'tests', ['tenant_id', 'is_active'], unique=False)
    op.create_index('ix_tests_is_deleted', 'tests', ['is_deleted'], unique=False)
    op.create_index('ix_tests_is_active', 'tests', ['is_active'], unique=False)
    op.create_index('ix_tests_code', 'tests', ['code'], unique=False)
    op.create_table('test_tree_backends',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('tenant_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('code', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('version', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='test_tree_backends_pkey')
    )
    op.create_index('ix_test_tree_backends_tenant_id', 'test_tree_backends', ['tenant_id'], unique=False)
    op.create_index('ix_test_tree_backends_tenant_deleted', 'test_tree_backends', ['tenant_id', 'is_deleted'], unique=False)
    op.create_index('ix_test_tree_backends_tenant_code', 'test_tree_backends', ['tenant_id', 'code'], unique=True)
    op.create_index('ix_test_tree_backends_tenant_active', 'test_tree_backends', ['tenant_id', 'is_active'], unique=False)
    op.create_index('ix_test_tree_backends_is_deleted', 'test_tree_backends', ['is_deleted'], unique=False)
    op.create_index('ix_test_tree_backends_is_active', 'test_tree_backends', ['is_active'], unique=False)
    op.create_index('ix_test_tree_backends_code', 'test_tree_backends', ['code'], unique=False)
    op.create_table('test_entities',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('tenant_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('code', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('price', sa.NUMERIC(), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('deactivated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('version', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='test_entities_pkey')
    )
    op.create_index('ix_test_entities_tenant_id', 'test_entities', ['tenant_id'], unique=False)
    op.create_index('ix_test_entities_tenant_code', 'test_entities', ['tenant_id', 'code'], unique=True)
    op.create_index('ix_test_entities_tenant_active', 'test_entities', ['tenant_id', 'is_active'], unique=False)
    op.create_index('ix_test_entities_is_active', 'test_entities', ['is_active'], unique=False)
    op.create_index('ix_test_entities_code', 'test_entities', ['code'], unique=False)
    op.create_table('test_basics',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('tenant_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('code', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('version', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='test_basics_pkey')
    )
    op.create_index('ix_test_basics_tenant_id', 'test_basics', ['tenant_id'], unique=False)
    op.create_index('ix_test_basics_tenant_deleted', 'test_basics', ['tenant_id', 'is_deleted'], unique=False)
    op.create_index('ix_test_basics_tenant_code', 'test_basics', ['tenant_id', 'code'], unique=True)
    op.create_index('ix_test_basics_tenant_active', 'test_basics', ['tenant_id', 'is_active'], unique=False)
    op.create_index('ix_test_basics_is_deleted', 'test_basics', ['is_deleted'], unique=False)
    op.create_index('ix_test_basics_is_active', 'test_basics', ['is_active'], unique=False)
    op.create_index('ix_test_basics_code', 'test_basics', ['code'], unique=False)
    op.create_table('test_trees',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('tenant_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('code', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('parent_test_tree_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('level', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('sort_order', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('version', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['parent_test_tree_id'], ['test_trees.id'], name='test_trees_parent_test_tree_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='test_trees_pkey')
    )
    op.create_index('ix_test_trees_tenant_id', 'test_trees', ['tenant_id'], unique=False)
    op.create_index('ix_test_trees_tenant_deleted', 'test_trees', ['tenant_id', 'is_deleted'], unique=False)
    op.create_index('ix_test_trees_tenant_code', 'test_trees', ['tenant_id', 'code'], unique=True)
    op.create_index('ix_test_trees_tenant_active', 'test_trees', ['tenant_id', 'is_active'], unique=False)
    op.create_index('ix_test_trees_parent_test_tree_id', 'test_trees', ['parent_test_tree_id'], unique=False)
    op.create_index('ix_test_trees_parent', 'test_trees', ['tenant_id', 'parent_test_tree_id'], unique=False)
    op.create_index('ix_test_trees_level', 'test_trees', ['level'], unique=False)
    op.create_index('ix_test_trees_is_deleted', 'test_trees', ['is_deleted'], unique=False)
    op.create_index('ix_test_trees_is_active', 'test_trees', ['is_active'], unique=False)
    op.create_index('ix_test_trees_code', 'test_trees', ['code'], unique=False)
    # ### end Alembic commands ###

