"""Add

Revision ID: f91c4df95d2a
Revises: cb2fbb5658ca
Create Date: 2025-12-20 09:46:37.214689

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f91c4df95d2a'
down_revision = 'cb2fbb5658ca'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('venues',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tenant_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_venues_code'), 'venues', ['code'], unique=False)
    op.create_index(op.f('ix_venues_is_active'), 'venues', ['is_active'], unique=False)
    op.create_index(op.f('ix_venues_is_deleted'), 'venues', ['is_deleted'], unique=False)
    op.create_index('ix_venues_tenant_active', 'venues', ['tenant_id', 'is_active'], unique=False)
    op.create_index('ix_venues_tenant_code', 'venues', ['tenant_id', 'code'], unique=True)
    op.create_index('ix_venues_tenant_deleted', 'venues', ['tenant_id', 'is_deleted'], unique=False)
    op.create_index(op.f('ix_venues_tenant_id'), 'venues', ['tenant_id'], unique=False)
    op.drop_index('ix_audit_logs_event_id', table_name='audit_logs')
    op.create_index('ix_audit_logs_event_id', 'audit_logs', ['event_id'], unique=False)
    op.drop_index('ix_audit_logs_event_type', table_name='audit_logs')
    op.create_index(op.f('ix_audit_logs_event_type'), 'audit_logs', ['event_type'], unique=False)
    op.drop_index('ix_item_categories_level', table_name='item_categories')
    op.create_index('ix_item_categories_level', 'item_categories', ['tenant_id', 'level'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_item_categories_level', table_name='item_categories')
    op.create_index('ix_item_categories_level', 'item_categories', ['level'], unique=False)
    op.drop_index(op.f('ix_audit_logs_event_type'), table_name='audit_logs')
    op.create_index('ix_audit_logs_event_type', 'audit_logs', ['event_type', 'timestamp'], unique=False)
    op.drop_index('ix_audit_logs_event_id', table_name='audit_logs')
    op.create_index('ix_audit_logs_event_id', 'audit_logs', ['event_id'], unique=True)
    op.drop_index(op.f('ix_venues_tenant_id'), table_name='venues')
    op.drop_index('ix_venues_tenant_deleted', table_name='venues')
    op.drop_index('ix_venues_tenant_code', table_name='venues')
    op.drop_index('ix_venues_tenant_active', table_name='venues')
    op.drop_index(op.f('ix_venues_is_deleted'), table_name='venues')
    op.drop_index(op.f('ix_venues_is_active'), table_name='venues')
    op.drop_index(op.f('ix_venues_code'), table_name='venues')
    op.drop_table('venues')
    # ### end Alembic commands ###

