"""Add canvas_background_color to layouts

Revision ID: fb9036cd7340
Revises: 5992b9e928d5
Create Date: 2026-02-09 23:43:01.012619

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb9036cd7340'
down_revision = '5992b9e928d5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('layouts', sa.Column('canvas_background_color', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('layouts', 'canvas_background_color')
    # ### end Alembic commands ###

